### ISSUE TITLE
swarm-plugin adds too many artifacts to the jar file

### ISSUE THREAD

**Issue by rjahn** [wildfly-swarm/wildfly-swarm#107]
Create a simple demo application with instructions: http://wildfly.org/swarm/
In my case, it was a hello world vaadin application.

The created "fat" jar contained too many artifacts in the m2repo directory, e.g. all my application dependencies. This is not needed because the created war archive contains all my application dependencies?

The file size was ~ 102MB. The automatically created jar was ~ 40MB. 
The overhead of ~62MB is too much!

I tried to create a "fat" swarm jar with an existing war archive (without maven build). The jar file was ~ 83 MB (the existing war was ~ 60MB). The overhead was ~ 23MB which was ok for the application server.

I had some problems with manual jar creation, because there's no documentation and BuildTool itself is tricky, but the application/"fat" jar was started without problems and my application was working without problems.

**Comment by kenfinnigan** [comment]
Is the issue you're describing above only that the `m2repo` contains jars that are provided in the WAR?

Why would you want to create a jar for WildFly Swarm manually? Is that a request you're making?

**Comment by rjahn** [comment]
Yes, the jars in the m2repo. The filesize was too large for the application. I did similar bundling with embedded Tomcat/TomEE and the overhead was very small.

I had a special use-case and I don't think it's a feature request. The official documentation contains:

> We do aim to add support for other build-systems in the near future.

First, I tried to integrate the build process in my ant script. This wasn't possible out-of-the-box because only gradle and maven are supported...

Why manually? There are existing build systems and CI server which create war files. It should be possible to take an existing war and create a "fat" jar. I want to know what happens behind the scene and which jars are needed for my project(s).

It's horrible if maven starts to download the internet because of some crazy dependencies...

**Comment by kenfinnigan** [comment]
WildFly Swarm is targeting a different use case than just plain "fat" jars, as we're focusing on providing byte size pieces of WildFly for use in "fat" jars.

At the moment, that often means that the eventual size of the "fat" jar is not as small as we would like, but there is room for work on making the modules of WildFly more independent, which would then reduce the size.

As you stated we currently have support for Maven and Gradle, and others will be added as we have time for it or as the community contributes has a need and contributes it.

You made reference to "manual jar creation", which I took to mean creating a jar manually. It is now apparent that is not what you meant, so you can ignore my comment on that.

I believe there was an issue raised for creating a "fat" jar from an existing WAR, but it's not something we've had a chance to investigate yet. The trick is figuring out what WildFly subsystems a WAR needs for it to work, and therefore which pieces from WildFly Swarm need to be included in a "fat" jar. If you would like to work on making this possible, that would be awesome

**Comment by jamesnetherton** [comment]
Any idea when we're likely to see swarm jars that are a bit more lightweight? 

I've been playing with the swarm example projects. Some of the generated jars weigh in at over 80Mb. There's a lot of stuff that's not relevant being packaged like CXF and all of its dependencies.

**Comment by bobmcwhirter** [comment]
If you can point us to an example app with a list of jars you think are extra we can begin to seek and destroy the extraneous stuff. 

--

**Comment by rjahn** [comment]
to kenfinnigan:

I think it's not important to create a jar from an existing war, without configuring relevant modules like JAX-RS. Automatic analyzation of war libs would be great, but maybe in a future release :)

Usually, the developer knows all required modules and can configure the build task. But the swarm build could be independent of war creation task. I have a war and know what modules are used. I could create a simple build task or (if needed) a maven project that creates the jar from my war, but I configure the dependencies manually.

I guess you know what I mean.

to bobmcwhirter:

My simple example project: https://github.com/rjahn/swarm

I'm sure that swarm doesn't need one of these libs: com.vaadin..., com.sibvisions..., javax.mail...

The jar had 102 MB....

**Comment by jamesnetherton** [comment]
@bobmcwhirter E.g the cdi-servlet demo. Taking a simplistic view of it, I see the words 'CDI' and 'Servlet' and assume my swarm jar will contain the minimum set of dependencies for the app server to support those two technologies. But it's stacked full of other stuff like Hibernate, CXF, HornetQ etc.

I guess this is a consequence of how things happen to be wired up in the underlying WildFly modules.

**Comment by kenfinnigan** [comment]
@jamesnetherton that's correct.

Every dependency that is pulled into the jar by Swarm is a result of how modules are defined within WildFly itself.

Trimming down those dependencies in WildFly itself is certainly a goal, but it requires work to validate that doing slimming doesn't impact WildFly.

**Comment by bobmcwhirter** [comment]
The above change reduced the -vaadin example -swarm.jar by about 40mb.
