### ISSUE TITLE
MDB Deployment Error

### ISSUE THREAD

**Issue by emag** [wildfly-swarm/wildfly-swarm#108]
Now I'm creating WildFly Swarm MDB sample.

https://github.com/emag/wildfly-swarm-examples/tree/mdb-spike/messaging-mdb

But, I got the following deployment error.

``` sh
Caused by: org.jboss.msc.service.ServiceNotFoundException:
  Service service jboss.ejb.default-resource-adapter-name-service not found
```
[full logs](https://gist.github.com/emag/5833078b428ca5e3e09d#file-error1-md)

So, I just added `default-resource-adapter-name` attribute in `EJBConfiguration`.

``` diff
$ git di
diff --git a/ejb/runtime/src/main/java/org/wildfly/swarm/ejb/runtime/EJBConfiguration.java b/ejb/runtime/src/main/java/org/wildfly/swarm/ejb/runtime/EJBConfiguration.java
index 3fe10f7..92b212b 100644
--- a/ejb/runtime/src/main/java/org/wildfly/swarm/ejb/runtime/EJBConfiguration.java
+++ b/ejb/runtime/src/main/java/org/wildfly/swarm/ejb/runtime/EJBConfiguration.java
@@ -49,6 +49,7 @@ public class EJBConfiguration extends AbstractServerConfiguration<EJBFraction> {
         node.get("default-singleton-bean-access-timeout").set(5000);
         node.get("default-security-domain").set("other");
         node.get("default-missing-method-permissions-deny-access").set("true");
+        node.get("default-resource-adapter-name").set("activemq-ra.rar");
         node.get("log-system-exceptions").set("true");
         list.add(node);
```

https://github.com/emag/wildfly-swarm/commit/0ade836a2bbac0df2d9ef7c46e7187bca3cdc4e4

Then, the error changed to the following one.

``` sh
ERROR [org.jboss.as.controller.management-operation] (main) WFLYCTL0013: Operation ("add") failed
  - address: (("deployment" => "5820c5f3-0937-4cad-b403-7802f96be063.war"))
  - failure description: {
    "WFLYCTL0180: Services with missing/unavailable dependencies" => 
      ["jboss.deployment.unit.\"5820c5f3-0937-4cad-b403-7802f96be063.war\".component.MyTopicMDB.CREATE is missing [
          jboss.ra.activemq-ra
        ]"
      ]
    }
```

[full logs](https://gist.github.com/emag/5833078b428ca5e3e09d#file-error2-md)

Do we need `resource-adapters` fraction or something ?

**Comment by bobmcwhirter** [comment]
Yah. Might need the connectors fraction as a dependency. 

--

**Comment by emag** [comment]
It means that the new fraction(corresponding `resource-adapters` subsystem) is needed?
Or, Do I have to add `wildfly-swarm-connector` dependency in my MDB sample(actually, it's already added for other dependencies)?

**Comment by bobmcwhirter** [comment]
I get confused as to which is which but we definitely already have a JCA subsystem. Messaging is in your example also?

--

**Comment by emag** [comment]
Yes, in my sample I define the following dependencies.

* wildfly-swarm-jaxrs
* wildfly-swarm-ejb
* wildfly-swarm-messaging

https://github.com/emag/wildfly-swarm-examples/blob/mdb-spike/messaging-mdb/pom.xml#L45-L59

Now I added wf-swarm-jca dependency explicitly, it was the same result.

**Comment by bobmcwhirter** [comment]
If you can point me to your repo I'll have time to look at it on Wednesday I think. 

--

**Comment by emag** [comment]
Thank you!

This is my MDB sample.

https://github.com/emag/wildfly-swarm-examples/tree/mdb-spike/messaging-mdb

``` sh
$ git clone https://github.com/emag/wildfly-swarm-examples.git && cd wildfly-swarm-examples && git checkout origin/mdb-spike
```
And this is my WF-Swarm fix.

https://github.com/emag/wildfly-swarm/commit/0ade836a2bbac0df2d9ef7c46e7187bca3cdc4e4

**Comment by bobmcwhirter** [comment]
@emag Your example now launches without error on the console.  If you could verify that it actually solves the problem also, that'd be stellar.

Thanks!

**Comment by emag** [comment]
Thanks a lot, it works!

Now, I have another question.

Although we can use JMS 2.0 API, it doesn't work.

https://github.com/emag/wildfly-swarm-examples/blob/mdb-spike/messaging-mdb/src/main/java/org/wildfly/swarm/examples/messaging/mdb/MyResource.java#L61

`@ JMSContext` and Topic Resource are not injected.

And I tried to define JMS destination by @ JMSDestinationDefinition, however, the same result(and it is not bounded).

https://github.com/emag/wildfly-swarm-examples/blob/mdb-spike/messaging-mdb/src/main/java/org/wildfly/swarm/examples/messaging/mdb/MyResource.java#L24-L28

Any idea?

## how to reproduce

You can test the following steps.

``` sh
git clone https://github.com/emag/wildfly-swarm-examples.git \
  && cd wildfly-swarm-examples \
  && git checkout origin/mdb-spike \
  && cd messaging-mdb \
  && mvn clean package && java -jar target/wildfly-swarm-example-messaging-mdb-swarm.jar
```

``` sh
curl localhost:8080/jms2
```

Then, you can see the stderr log in server(WF-Swarm) side.

``` sh
>>>>>>>>>>>>>>>
JMSContext: null
Topic: null
<<<<<<<<<<<<<<<
```

**Comment by bobmcwhirter** [comment]
No idea but I'll investigate tomorrow!

**Comment by bobmcwhirter** [comment]
Sorry I dropped this.  Looking into it now.

**Comment by bobmcwhirter** [comment]
Okay...

if you add @Stateless to MyResource, it fails a little more correctly, but still fails.

I'm pretty ignorant of JNDI and lookups, but I think it requires @Stateless on it to get injections to start working. 

Let me know.

**Comment by emag** [comment]
Thank you for your comment.

Yeah, I forgot to add CDI or EJB Annotation for MyResource, sorry.

Now  I added it(in my case, @ApplicationScoped), and I got `NameNotFoundException: DefaultJMSConnectionFactory`.

Even though WildFly Swarm startup log says DfaultJMSConnectionFactory is bounded, it seems that it has some problem.

``` sh
FLYMSGAMQ0002: Bound messaging object to jndi name java:jboss/DefaultJMSConnectionFactory
```

I'll look into it a little bit more. Thanks.
javax.naming.NameNotFoundException: DefaultJMSConnectionFactory

**Comment by bobmcwhirter** [comment]
Yah, I'm looking into that now.

**Comment by bobmcwhirter** [comment]
Okay, I have a fix to push (shortly, once my local tests complete) to fix the DefaultJMSConnectionFactory issue.

**Comment by emag** [comment]
Thank you for your fix, it works!

I'll clean up my mdb sample and then do p-r for wildfly-swarm-example later.

**Comment by bobmcwhirter** [comment]
Glad to hear it!

Also, never hesitate to poke an issue if we've let it linger for a while without fixing.  We lose track sometimes.

**Comment by emag** [comment]
OK, thanks :)
