### ISSUE TITLE
Application not accessible on localhost

### ISSUE THREAD

**Issue by arun-gupta** [wildfly-swarm/wildfly-swarm#11]
Created a simple JAX-RS sample as at:

https://github.com/arun-gupta/wildfly-samples/tree/master/swarm

The application is accessible at http://127.0.0.1:8080/resources/resource but not at http://localhost:8080/resources/resource. This is using `curl`. Both the URLs work from the browser.

Error log from localhost:
```
curl -v http://localhost:8080/resources/resource
* Hostname was NOT found in DNS cache
*   Trying ::1...
* connect to ::1 port 8080 failed: Connection refused
*   Trying fe80::1...
* connect to fe80::1 port 8080 failed: Connection refused
* Failed to connect to localhost port 8080: Connection refused
* Closing connection 0
curl: (7) Failed to connect to localhost port 8080: Connection refused
```

Log from 127.0.0.1:
```
curl -v http://127.0.0.1:8080/resources/resource
* Hostname was NOT found in DNS cache
*   Trying 127.0.0.1...
* Connected to 127.0.0.1 (127.0.0.1) port 8080 (#0)
> GET /resources/resource HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 127.0.0.1:8080
> Accept: */*
> 
< HTTP/1.1 200 OK
< Connection: keep-alive
< Content-Type: application/octet-stream
< Content-Length: 12
< Date: Wed, 06 May 2015 19:29:10 GMT
< 
* Connection #0 to host 127.0.0.1 left intact
hello swarm!
```

**Comment by kenfinnigan** [comment]
Is it fixed if you take the answer from -> http://superuser.com/questions/830920/curl-local-host-names-on-mac-os-x-yosemite ?

**Comment by bobmcwhirter** [comment]
By default Undertow binds to 127.0.0.1

https://github.com/wildfly-swarm/wildfly-swarm/blob/master/container/src/main/java/org/wildfly/swarm/container/Container.java#L150

This can be overridden by using

    java -Djboss.bind.address=0.0.0.0 -jar myapp-swarm.jar

Alternatively, maybe we could make 0.0.0.0 the default, to bind to all interfaces instead of just 127.0.0.1.

Your failure with `localhost` seems to be IPv6-related, I think.  I'm pretty ignorant of IPv6 and Undertow.

**Comment by arun-gupta** [comment]
Binding to `0.0.0.0` is very reasonable. This is what is done for Docker images as well.
