### ISSUE TITLE
Ribbon.js/RibbonToTheCurbSSEServlet

### ISSUE THREAD

**Issue by bobmcwhirter** [wildfly-swarm/wildfly-swarm#125]
The booker demo uses a custom ribbon.js and RibbonToTheCurbSSEServlet.  It'd be nice to somehow integrate those directly into wildfly-swarm-ribbon.

**Comment by lance** [comment]
Fixed.
See example usage here: https://github.com/wildfly-swarm/booker/tree/master/web-client
