### ISSUE TITLE
Getting "Unable to create default deployment" when running via maven

### ISSUE THREAD

**Issue by jclingan** [wildfly-swarm/wildfly-swarm#137]
I have a simple application ([link](https://github.com/jclingan/simple-wildfly-swarm-app)) that creates a hello world JAX-RS resource. The application runs fine via "java -jar", but I get a warning when trying to run the app via "mvn wildfly-swarm:run".

Warning: ERROR [stderr] (main) [WARN] Unable to create default deployment.

**Comment by bobmcwhirter** [comment]
Same problem as reported in #133, fixed in HEAD.

Build from git, use 1.0.0.Alpha5-SNAPSHOT and add

            <version>${version.wildfly-swarm}</version>

to your wildfly-swarm-plugin to ensure that version is used during the build also (I think mvn uses the latest non-SNAPSHOT by default)

**Comment by jclingan** [comment]
Many thanks.

**Comment by jclingan** [comment]
Using alpha5-SNAPSHOT fixed it. Thanks again.
