### ISSUE TITLE
List available Fractions as a separate maven artifact

### ISSUE THREAD

**Issue by gastaldi** [wildfly-swarm/wildfly-swarm#138]
It would be nice to have a YAML/JSON/XML file containing the available Wildfly-Swarm Fractions. This would help in https://github.com/forge/wildfly-swarm-addon/issues/1

**Comment by bobmcwhirter** [comment]
Just a straight list, or would having dependency information be useful?

e.g. -> 

    { 
      "jaxrs" : [ "undertow" ],
     "undertow" : [ "container", "naming" ]
    }

**Comment by kenfinnigan** [comment]
This got me thinking that if the json had deps, we could create a fraction scaffolder that takes JSON of the above form and defines all the necessary projects with appropriate maven deps for a new fraction

**Comment by gastaldi** [comment]
The dependency information would be nice to have too

**Comment by gastaldi** [comment]
how about a DOT file? We use that in Forge for visualizing addon dependencies

**Comment by bobmcwhirter** [comment]
For now, just a simple file will be available on the next release:

    <groupId>org.wildfly.swarm</groupId>
    <artifactId>wildfly-swarm-fraction-list</artifactId>
    <type>txt</type>

It contains a list of available fractions, one-per-line, a colon-separated groupId:artifactId

The current contents, as of this writing, is:

```
org.wildfly.swarm:wildfly-swarm-bean-validation
org.wildfly.swarm:wildfly-swarm-clustering
org.wildfly.swarm:wildfly-swarm-connector
org.wildfly.swarm:wildfly-swarm-container
org.wildfly.swarm:wildfly-swarm-datasources
org.wildfly.swarm:wildfly-swarm-ee
org.wildfly.swarm:wildfly-swarm-ejb
org.wildfly.swarm:wildfly-swarm-ejb-remote
org.wildfly.swarm:wildfly-swarm-hawkular
org.wildfly.swarm:wildfly-swarm-infinispan
org.wildfly.swarm:wildfly-swarm-io
org.wildfly.swarm:wildfly-swarm-jaxrs
org.wildfly.swarm:wildfly-swarm-jca
org.wildfly.swarm:wildfly-swarm-jmx
org.wildfly.swarm:wildfly-swarm-jolokia
org.wildfly.swarm:wildfly-swarm-jpa
org.wildfly.swarm:wildfly-swarm-jsf
org.wildfly.swarm:wildfly-swarm-keycloak
org.wildfly.swarm:wildfly-swarm-logging
org.wildfly.swarm:wildfly-swarm-logstash
org.wildfly.swarm:wildfly-swarm-mail
org.wildfly.swarm:wildfly-swarm-messaging
org.wildfly.swarm:wildfly-swarm-msc
org.wildfly.swarm:wildfly-swarm-naming
org.wildfly.swarm:wildfly-swarm-remoting
org.wildfly.swarm:wildfly-swarm-ribbon
org.wildfly.swarm:wildfly-swarm-ribbon-secured
org.wildfly.swarm:wildfly-swarm-security
org.wildfly.swarm:wildfly-swarm-transactions
org.wildfly.swarm:wildfly-swarm-undertow
org.wildfly.swarm:wildfly-swarm-weld
```

**Comment by tobias** [comment]
@bobmcwhirter - you asked on irc if this would be useful for swarmtool - it would if it also included packages that indicate the fraction should be included, but that would have to be manually generated. swarmtool currently uses https://github.com/wildfly-swarm/wildfly-swarm/blob/master/swarmtool/src/main/resources/org/wildfly/swarm/swarmtool/fraction-packages.properties to specify that.
