### ISSUE TITLE
Dependency version mismatch from config-api

### ISSUE THREAD

**Issue by kenfinnigan** [wildfly-swarm/wildfly-swarm#140]
I noticed that the contents of WEB-INF/lib of a generated WAR archive that is deployed to the container has a reasonable amount of dependency duplication but with different versions.

After some digging I found that the version of wildfly-core that is part of WildFly, which wildfly-swarm uses, is more recent than the one being used directly by config-api.

Not sure the best solution, but one option is a BOM project that is external to both wildfly-swarm and config-api that defines these versions, which they both then import

**Comment by bobmcwhirter** [comment]
I think config-api also needs some scope adjustments on its depa maybe. 

--

**Comment by bobmcwhirter** [comment]
I've moved to a <scope>import</scope> in the dependencyManagement of config-api, bringing in wildfly-parent (based on WF's version) and removing any explicit wildfly-core versioning.

As long as the same WF version is used, we should be good now.

**Comment by kenfinnigan** [comment]
Awesome!
