### ISSUE TITLE
https only in wildfly-swarm

### ISSUE THREAD

**Issue by thomasmey** [wildfly-swarm/wildfly-swarm#141]
Hi,

how to configure a https only connector in wildfly-swarm
			container.subsystem(new UndertowFraction() {
				@Override
				public void initialize(Container.InitContext initContext) {
					initContext.socketBinding(new SocketBinding("https").port(port));
				}
			});

But this fails because of a missing configuration for the http listener.

See also https://github.com/thomasmey/einkaufsliste-server/blob/HEAD/src/main/java/de/m3y3r/cloud/App.java

Btw. how to specifiy an servlet filter for an JAXRS deploment, I want to realize a rate limiting for the JAX-RS stuff via a servlet filter, do I just need to create a web.xml and set the filter or does the deployment via JaxrsDeployment (shrinkwrap) imply something else?

with kind regards
thomas

**Comment by emag** [comment]
>  do I just need to create a web.xml

Since Servlet 3.0, you can add filters by @ WebFilter(filterName="foo-filter", urlPatterns="/foo"), so you don't have to craete a web.xml.

https://docs.oracle.com/javaee/7/api/javax/servlet/annotation/WebFilter.html

**Comment by bobmcwhirter** [comment]
Try adding the socket-binding to the container instead of in the initialize. Then a filter to force redirect from http to https maybe. 

We can probably make it easier though of course. 

--

**Comment by bobmcwhirter** [comment]
How are you configuring the keystore and things required by https?  We'll definitely have more knobs and such in the next release of WildFly-Swarm, but if we can figure out the usage patterns, we can make http+https (or https-only) even easier.
