### ISSUE TITLE
Add interceptor spec dependency

### ISSUE THREAD

**Issue by emag** [wildfly-swarm/wildfly-swarm#146]
Now WildFly Swarm modules don't have Interceptor spec dependency, so you need to add it in your app manually to use Interceptor API(javax.interceptor.*).

``` xml
<dependency>
  <groupId>org.jboss.spec.javax.interceptor</groupId>
  <artifactId>jboss-interceptors-api_1.2_spec</artifactId>
  <version>1.0.0.Final</version>
  <scope>provided</scope>
</dependency>
```

Would it better WF-Swarm  add the spec dependency in any existing modules, or create a module for  interceptor?

**Comment by bobmcwhirter** [comment]
Give HEAD (Alpha6-SNAPSHOT) a whirl.  The correct modules should already be pulled in.  I added the above as dependencies of

* wildfly-swarm-ee
* wildfly-swarm-ejb
* wildfly-swarm-weld

If you find other places that it should be implicitly available, let me know.

**Comment by emag** [comment]
Thanks you for your commit! Now I can remove the explicit interceptor api spec dependency.

> If you find other places that it should be implicitly available, let me know.

Sure :) But I have a (probably myopic) thought.

As you and Tomaz said on hipchat, it seems WildFly Distro several modules depend on interceptor api spec and its implements(jboss-invocation). It' hard to know what subsystem is responsible for it.

However, personally speaking, in WildFly Swarm side, since most modules depend on wildfly-swarm-ee, it's satisfied only by adding it to wildfly-swarm-ee....

**Comment by bobmcwhirter** [comment]
If you confirmed that this works, can we close this?

**Comment by emag** [comment]
Just now, I confirmed and did p-r https://github.com/wildfly-swarm/wildfly-swarm/pull/147

I tested it by the following tiny sample.

https://github.com/emag/professional-java-ee-design-patterns/tree/master/interceptor
