### ISSUE TITLE
war.staticContent() looks for static content in $PWD, even when run from a fatjar

### ISSUE THREAD

**Issue by bbrowning** [wildfly-swarm/wildfly-swarm#151]
Take the following code example:
```
 WARArchive war = ShrinkWrap.create(WARArchive.class);
 war.staticContent();
```
When run from a `foo-swarm.jar`, that code looks for static content relative to $PWD. Instead, it should look for the static content inside the jar. It doesn't appear src/main/resources/ ends up inside the -swarm.jar by default, or at least not in the web-client of our booker sample app, so perhaps it is looking in the jar first and falling back to $PWD?

Either way, we need to figure out the right way to handle static assets when run from a fatjar.

**Comment by bobmcwhirter** [comment]
Static has been a problem continuously. A reworking of it would be lovely.

--
Sent from my iPhone


On Nov 5, 2015, at 11:53 AM, Ben Browning <notifications@github.com> wrote:

Take the following code example:

 WARArchive war = ShrinkWrap.create(WARArchive.class);
 war.staticContent();

When run from a foo-swarm.jar, that code looks for static content relative
to $PWD. Instead, it should look for the static content inside the jar. It
doesn't appear src/main/resources/ ends up inside the -swarm.jar by
default, or at least not in the web-client of our booker sample app, so
perhaps it is looking in the jar first and falling back to $PWD?

Either way, we need to figure out the right way to handle static assets
when run from a fatjar.

—
Reply to this email directly or view it on GitHub
<https://github.com/wildfly-swarm/wildfly-swarm/issues/151>.

**Comment by bbrowning** [comment]
I looked at this a bit and there are a couple of problems in play when going between running from disk and running in a jar that have to be figured out.

- When running in a JAR we only look for static content inside that JAR using a ClassPathResourceManager. That resource manager assumes you pass a complete path to every resource and does not look for index files (index.html, index.htm, etc) when given a directory.

- ClassPathResourceManager only finds resources on the classpath. We install two of these - one with the system classloader and one with the swarm bootstrap classloader. Neither of these appear to pickup static resources that end up in _bootstrap/booker-web-client-version.jar.

- We're too liberal with what we match for static resources, allowing someone to easily trick Swarm into serving up the actual .class files of the application as a static resource. Oops.
