### ISSUE TITLE
wildfly-swarm-bootstrap not in internal repo of swarm fat jar

### ISSUE THREAD

**Issue by btison** [wildfly-swarm/wildfly-swarm#162]
Hi,

is there a reason why wildfly-swarm-bootstrap is not added to the m2repo folder in the swarm fat jar when building with the wildfly-swarm-plugin plugin?
The reason I am asking is that when I run a swarm jar in an environment that has no maven installed (e.g. a docker container) my jar fails to start. From debugging it seems the bootstrap process tries to resolve the wildfly-swarm-bootstrap from the maven repo in the swarm jar. It doesn't find it there, so it tries to resolve from the local maven repo, and as it is not found there, from public maven repos (maven central, jboss public repo), where it can't find it neither. The end result is that my jar fails to start.
When I manually add the wildfly-swarm-bootstrap jar in the m2repo folder of my fat jar, everything works fine. 

Thx

Bernard

**Comment by btison** [comment]
Forgot to add I am using 1.0.0.Alpha6-SNAPSHOT.

**Comment by bobmcwhirter** [comment]
Hrm, that's intentional since the contents are exploded into the -swarm.jar
itself. Apparently I've done something wrong though. Can you attach or gist
the error you see?

--
Sent from my iPhone


On Nov 17, 2015, at 5:42 AM, Bernard Tison <notifications@github.com> wrote:

Forgot to add I am using 1.0.0.Alpha6-SNAPSHOT.

—
Reply to this email directly or view it on GitHub
<https://github.com/wildfly-swarm/wildfly-swarm/issues/162#issuecomment-157332883>
.

**Comment by btison** [comment]
The error says the moduleloader cannot find the modules:
---
Exception in thread "main" org.jboss.modules.ModuleNotFoundException: org.wildfly.swarm.logging:main
        at org.jboss.modules.Module.addPaths(Module.java:1042)
        at org.jboss.modules.Module.link(Module.java:1398)
        at org.jboss.modules.Module.relinkIfNecessary(Module.java:1426)
        at org.jboss.modules.ModuleLoader.loadModule(ModuleLoader.java:238)
        at org.wildfly.swarm.bootstrap.Main.getMainClass(Main.java:73)
        at org.wildfly.swarm.bootstrap.Main.run(Main.java:50)
        at org.wildfly.swarm.bootstrap.Main.main(Main.java:39)
---

However I think the real error is already happening before that, in org.wildfly.swarm.bootstrap.util.Layout.determineBootstrapClassLoader(). That method tries to load the org.wildfly.swarm.bootstrap module. It finds the module through the BootstrapModuleFinder, which then tries to build the module (org.wildfly.swarm.bootstrap.modules.AbstractSingleModuleFinder.buildModule(Builder, ModuleLoader). The implementation reads the META-INF/wildfly-swarm-bootstrap.conf file, and tries to load all artifacts in this file through maven. 
The contents of my META-INF/wildfly-swarm-bootstrap.conf is:
----
org.wildfly.swarm:wildfly-swarm-security-modules:1.0.0.Alpha6-SNAPSHOT
org.wildfly.swarm:wildfly-swarm-webservices-modules:1.0.0.Alpha6-SNAPSHOT
org.wildfly.swarm:wildfly-swarm-undertow-modules:1.0.0.Alpha6-SNAPSHOT
org.wildfly.swarm:wildfly-swarm-container-modules:1.0.0.Alpha6-SNAPSHOT
org.wildfly.swarm:wildfly-swarm-logging-modules:1.0.0.Alpha6-SNAPSHOT
org.wildfly.swarm:wildfly-swarm-io-modules:1.0.0.Alpha6-SNAPSHOT
org.wildfly.swarm:wildfly-swarm-bootstrap:1.0.0.Alpha6-SNAPSHOT
org.wildfly.swarm:wildfly-swarm-naming-modules:1.0.0.Alpha6-SNAPSHOT
org.wildfly.swarm:wildfly-swarm-ee-modules:1.0.0.Alpha6-SNAPSHOT
----

The  META-INF/wildfly-swarm-bootstrap.conf contains 'org.wildfly.swarm:wildfly-swarm-bootstrap:1.0.0.Alpha6-SNAPSHOT', so the implementation tries to load it through maven, and fails. The BootstrapModuleFinder throws a ModuleNotFoundException which is catched by Layout.determineBootstrapClassLoader(), which sets the bootstrap classloader to the classloader of the LayoutClass (an instance of sun.misc.Launcher$AppClassLoader) instead of an instance of ModuleClassLoader.

So it looks like META-INF/wildfly-swarm-bootstrap.conf should not contain org.wildfly.swarm:wildfly-swarm-bootstrap.

Bernard

**Comment by bobmcwhirter** [comment]
Thank you for the fantastic report.  I’m investigating now.

**Comment by bobmcwhirter** [comment]
I've tried this against an -example as usual and with -Dmaven.repo.local=./tmp to point to an empty maven repo, and both work, along with `mvn wildfly-swarm:run`.

Give it a whirl and let me know if this solves your problem

Once again, this bug report was terrific and helped very much in tracking this down.  Keep up the good work!
