### ISSUE TITLE
Maven 'packaging' element not inferred.

### ISSUE THREAD

**Issue by dansiviter** [wildfly-swarm/wildfly-swarm#164]
The default packaging in Maven is `jar` however if this element is missing `org.wildfly.swarm.container.Container#determineDeploymentType` will return `unknown` even though we can infer that it would be `jar`.

**Comment by bobmcwhirter** [comment]
Great. That is easily fixable.

--
Sent from my iPhone


On Nov 19, 2015, at 7:36 AM, dansiviter <notifications@github.com> wrote:

The default packaging in Maven is jar however if this element is missing
org.wildfly.swarm.container.Container#determineDeploymentType will return
unknown even though we can infer that it would be jar.

—
Reply to this email directly or view it on GitHub
<https://github.com/wildfly-swarm/wildfly-swarm/issues/164>.

**Comment by dansiviter** [comment]
Thanks!
