### ISSUE TITLE
CDI doesn't work

### ISSUE THREAD

**Issue by emag** [wildfly-swarm/wildfly-swarm#19]
Although I apply [weld-fraction(and some dependent fraction)](https://github.com/emag/wildfly-swarm-quickstarts/blob/master/jaxrs-cdi/pom.xml#L41-L58), I can't use CDI features.

In this my sample, a field added @ Inject is not injected. 

https://github.com/emag/wildfly-swarm-quickstarts/blob/master/jaxrs-cdi/src/main/java/wildflyswarm/jaxrscdi/api/EmployeeController.java#L22

Classes added @ ApplicationScoped are not registered.

* https://github.com/emag/wildfly-swarm-quickstarts/blob/master/jaxrs-cdi/src/main/java/wildflyswarm/jaxrscdi/api/EmployeeController.java#L17
* https://github.com/emag/wildfly-swarm-quickstarts/blob/master/jaxrs-cdi/src/main/java/wildflyswarm/jaxrscdi/domain/service/EmployeeService.java#L12

**Comment by smiklosovic** [comment]
this is a must for my use case as well

**Comment by bobmcwhirter** [comment]
That's awesome!

--

**Comment by smiklosovic** [comment]
nice!

**Comment by emag** [comment]
Great! :)
