### ISSUE TITLE
static content sample

### ISSUE THREAD

**Issue by kenfinnigan** [wildfly-swarm/wildfly-swarm#21]
_From @eprogramming on May 13, 2015 10:16_

hi @kenfinnigan , how we can use index.html / *.css / *.js ?
thanks for this example + 1

_Copied from original issue: wildfly-swarm/example-servlet-cdi#1_

**Comment by kenfinnigan** [comment]
Do you have an example project/repo of what you're looking to achieve?

Might be easier to convert that to work with WildFly Swarm

**Comment by kenfinnigan** [comment]
_From @eprogramming on May 13, 2015 15:12_

@kenfinnigan 

yup https://github.com/aeshell/nanook/tree/with-wildfly-swarm

I just need *.css *.js *.html

**Comment by kenfinnigan** [comment]
_From @bobmcwhirter on May 13, 2015 15:14_

Yah, I'd definitely like to make static resources easy to serve.  Dunno if that's some flavor of StaticResourceDeployment or something else.  Configuring a resource-servlet is a pain when you just want to serve up files from within the jar or filesystem.

**Comment by kenfinnigan** [comment]
_From @eprogramming on May 13, 2015 15:20_

@bobmcwhirter 
this feature would be very good

+1

**Comment by eprogramming** [comment]
hi, this web framework handles static resources using undertow:
(Java micro web framework built on top of Undertow)

https://github.com/EsmerilProgramming/overtown
here is a blog post ('cloverx' is the old name of the framework)
http://eprogramming.github.io/blog/2015/2/10.html

**Comment by ctomc** [comment]
@kenfinnigan @bobmcwhirter you guys could just configure undertow subsystem to handle this.
maybe by hiding it by some nicer api. but it is out of the box functionality subsystem provides.

**Comment by eprogramming** [comment]
Awesome !
you guys rock !

**Comment by kenfinnigan** [comment]
@ctomc can you point to an example of what config would be required?

**Comment by ctomc** [comment]
@kenfinnigan an example would be welcome content handler we have by default in undertow subsystem.
you first add file-handler: 
https://github.com/wildfly/wildfly/blob/master/undertow/src/main/resources/subsystem-templates/undertow.xml#L45
and then "mount" it to what ever context you want. in our default shipped config
https://github.com/wildfly/wildfly/blob/master/undertow/src/main/resources/subsystem-templates/undertow.xml#L35

in terms of mgmt ops that would be something along lines (not tested)
/subsystem=undertow/configuration=handlers/file=my-new-handler:add(path=/path/to/static/content, extra-params...)

and than
/subsystem=undertow/server=<name-of-server>/host=<name-of-host>/location=/:write-attribute(handler=my-new-handler)

but you probably get the idea.
ping me on hipchat if you need more info.

**Comment by eprogramming** [comment]
Awesome !
Thanks !

**Comment by bobmcwhirter** [comment]
Example:  

https://github.com/wildfly-swarm/examples/blob/master/static/src/main/java/org/wildfly/swarm/examples/staticcontent/Main.java

Let me know if it's not what you're thinking.  It does *not* mix static into normal war deployments, but rather is static-as-a-deployment-unto-itself.

Probably sub-par.  Reopen if not sufficient.

**Comment by eprogramming** [comment]
thanks @bobmcwhirter ! : D

**Comment by eprogramming** [comment]
not running : /
to do a double check i did a checkout on 
https://github.com/wildfly-swarm/examples/tree/master/static
the console don't fire up the container here

**Comment by eprogramming** [comment]
but i know it will work : ]

**Comment by bobmcwhirter** [comment]
Did you build -swarm itself from HEAD?

--

**Comment by eprogramming** [comment]
yes @jamezp is investigating this too

@jamezp thanks  a lot !

**Comment by eprogramming** [comment]
@bobmcwhirter i'm using a clean new fedora22 so i downloaded all for the first time
different from +-20 days ago.

**Comment by jamezp** [comment]
None of the examples work for me. I think the issues is that [entry point](https://github.com/jamezp/wildfly-swarm/blob/master/bootstrap/src/main/java/org/wildfly/swarm/bootstrap/Main.java#L37-37) tries to load the module as do the [ModuleFinders](https://github.com/jamezp/wildfly-swarm/blob/master/bootstrap/src/main/java/org/wildfly/swarm/bootstrap/util/Layout.java#L78). This ends up just sitting in a [`Object.wait()`](https://github.com/jboss-modules/jboss-modules/blob/1.4.3.Final/src/main/java/org/jboss/modules/Module.java#L1345).

**Comment by jamezp** [comment]
What I meant to add was this doesn't seem right. I don't think both the `ModuleFinder`'s and the entry point should be attempting to load the same module. That looks like trouble to me.

**Comment by bobmcwhirter** [comment]
I'm confused. Alpha2? HEAD?

--

**Comment by bobmcwhirter** [comment]
And that entry point has been working for a while. There is some magic wrt bootstrap. 

I've seen the object wait inside module getPaths or whatnot but though we had solved it. 

Sigh. 

--

**Comment by jamezp** [comment]
Sorry yes this is on head.

**Comment by jamezp** [comment]
Stupid laptop pressing buttons with my palm... ...I was trying to add. I can probably look at it this weekend. I see what the intent is with different ways to determine where modules are. We just need to way not to make it so racy I think.

**Comment by bobmcwhirter** [comment]
Double check all the code paths. Bootstrap itself is loaded differently but cannot have dependencies on ClasspathModuleFinder loaded modules. Hence the BootstrapClasspathModuleFinder. 

It's weird but works. Mostly. 

--

**Comment by eprogramming** [comment]
@bobmcwhirter you write:

> Configuring a resource-servlet is a pain when you just want to serve up files from within the jar or filesystem.

Hail 'pain' all fine ?

@bobmcwhirter predicting the future?

you're right, but I trust it will work

btw this is important, imagine to have hawtio + angular and others running from a jar how awesome is that ?

**Comment by jamezp** [comment]
The issue is definitely the `ClassPathModuleFinder`. What happens is the module loading state is `LINKING`, then the `ClassPathModuleFinder` attempts [get a resource](https://github.com/jamezp/wildfly-swarm/blob/master/bootstrap/src/main/java/org/wildfly/swarm/bootstrap/modules/ClasspathModuleFinder.java#L26) from the class path. Since the paths are still linking it essentially deadlocks.

I don't have a good solution for this though... ...well any solution at this point. One thing that *may* work would be to ensure anything that main class needs are loaded as local resources. Not that I have a good idea how to do that either :)

**Comment by jamezp** [comment]
I think I found it. The default `javax.api` module has a dependency on `javax.sql.api`. That module doesn't exist so adding it seems to get past this issue.

```xml
<?xml version="1.0" encoding="UTF-8"?>
<module xmlns="urn:jboss:module:1.3" name="javax.sql.api">
    <resources>
        <artifact name="org.jboss.spec.javax.sql:jboss-javax-sql-api_7.0_spec:1.0.1.Final"/>
    </resources>

    <dependencies>
        <module name="javax.api"/>
    </dependencies>
</module>
```

We should probably import some things from the core-feature-pack so we don't need to maintain them here.

I did find another issue with JDK 7 and the logmanager though. Something appears to be using logging before the logmanager is set... ...anyway that's a secondary issue.

**Comment by bobmcwhirter** [comment]
Can you give m steps to reproduce and the what module or resources it's trying to load?

--

**Comment by jamezp** [comment]
All I have to do is do a `mvn clean package && java -jar target/wildfly-swarm-example-static-swarm.jar` or just `mvn clean wildfly-swarm:run`. Either way it just sits there blocked. This is the simple and quick fix https://github.com/wildfly-swarm/wildfly-swarm/compare/master...jamezp:deadlock-fix

**Comment by bobmcwhirter** [comment]
The sql module should be in bootstrap/src/main/resources/modules. I added it yesterday unless I mis-used git. 

--

**Comment by jamezp** [comment]
Hmm... ...I definitely don't see it on master https://github.com/wildfly-swarm/wildfly-swarm/tree/master/bootstrap/src/main/resources/modules.

**Comment by bobmcwhirter** [comment]
Well dang. That'd be explain why I didn't see the same thing. Yah I have that javax.sql module in my tree. 



--

**Comment by jamezp** [comment]
haha, well at least we know :) I couldn't figure out how you would have got it working. Maybe you just forgot to push it upstream.

**Comment by bobmcwhirter** [comment]
Mayhap. We will find out Monday when I open the laptop. 

The JDK 7 logmanager thing I've seen. No idea why. Solution is JDK 8. 

--

**Comment by jamezp** [comment]
Cool. I'll have a look at some point. It should be fairly easy to fix.

**Comment by bobmcwhirter** [comment]
Okay, javax.sql module added back to HEAD.  Dunno how I managed that.

**Comment by bobmcwhirter** [comment]
See also https://github.com/wildfly-swarm/wildfly-swarm/issues/49 for static-content-within-a-war.

**Comment by emag** [comment]
@eprogramming and I got 403 Forbidden in [static example](https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/master/static) at wf-swarm HEAD(c08f4cf).

``` sh
$ mvn clean package && java -jar target/wildfly-swarm-example-static-swarm.jar
...
2015-06-17 06:50:08,664 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-13) WFLYUT0021: Registered web context: /static
2015-06-17 06:50:08,668 INFO  [org.jboss.as.server] (main) WFLYSRV0010: Deployed "8c51b8af-a3dd-44ae-92a3-8d0f02b46aba.war" (runtime-name : "8c51b8af-a3dd-44ae-92a3-8d0f02b46aba.war")
```

``` sh
$ curl localhost:8080/static/ -I
HTTP/1.1 403 Forbidden
...
```

But, it works when a contex path is `/` .

``` sh
2015-06-17 06:57:22,949 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-13) WFLYUT0021: Registered web context: /
```

``` sh
$ curl localhost:8080 -I
HTTP/1.1 403 Forbidden
...
```

``` sh
$ curl localhost:8080/index.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>WildFly Swarm JSF</title>
</head>
<body>
  <h1>Hello, JSF!</h1>
</body>
</html>%                
```

I changed from `new StaticDeployment(container, "/static")` to `new StaticDeployment(container)`

https://github.com/emag/wildfly-swarm-quickstarts/blob/master/jsf/src/main/java/wildflyswarm/jsf/App.java#L14

**Comment by eprogramming** [comment]
+1

**Comment by bobmcwhirter** [comment]
Hrm. I'll check into it tomorrow morning  

Thanks!

--

**Comment by ctomc** [comment]
that forbidden error, could it be related to folder listing?

**Comment by eprogramming** [comment]
https://github.com/wildfly-swarm/wildfly-swarm/issues/49 
awesome !
now I can move forward 
thanks !
I'm running index.html and a servlet

**Comment by eprogramming** [comment]
Thanks for all support !
It is working  Æsh + wildfly-swarm 

![nanook](https://cloud.githubusercontent.com/assets/6443576/8197992/9acd5544-1476-11e5-8728-b219708a8897.png)

**Comment by bobmcwhirter** [comment]
So we need to get index.html serving implicitly?

--

**Comment by eprogramming** [comment]
@bobmcwhirter i guess this would be great , for now the root path we get 'Forbidden' since we have no 'welcome-file' web.xml , is needed to point to index.html.
(If I understand well your question)

**Comment by bobmcwhirter** [comment]
Lemme look how welcome files work. I'd think any path that results in a subdir not just root should attempt an index.html for ease of use. 

--

**Comment by ctomc** [comment]
@bobmcwhirter not sure how you did your integration but on ResourceHandler you have welcome file list you can set. By default it is index.html", "index.htm", "default.html", "default.htm"

**Comment by bobmcwhirter** [comment]
We are using ResourceHandler. 

--

**Comment by eprogramming** [comment]
@bobmcwhirter 
 
no need more to point to index.html directly
just localhost:8080
thanks again !

**Comment by bobmcwhirter** [comment]
We aim to please. Keep reporting any issues you find and we will keep fixing them!

--

**Comment by eprogramming** [comment]
Ok !
I have a issue right now !
but the question is:
```
is good to use the github  or try hipchat before.. to discuss ?
```
because i don't know about all the aims and objectives of wildfly-swarm and i don't know if is good to open an issue not related with it.

**Comment by eprogramming** [comment]
hi all 
I got lot of ideas and tips from @jamezp and @ctomc on https://www.hipchat.com/gW90m6pIs

So I was wondering about the final jar size and because some dependencies were there.

Thanks !

**Comment by bobmcwhirter** [comment]
It never hurts to open issues. 

--

**Comment by eprogramming** [comment]
@bobmcwhirter the talk was about eclipse jdt compiler for JSPs, the picketbox and others dependencies that the project i'm contributing is not needed. but... the folks said this is important for others projects that use this and some deps are required .
well i understand like this.

**Comment by eprogramming** [comment]
@kenfinnigan @bobmcwhirter
https://gist.github.com/eprogramming/8a12fe502b38ba516f71
jansi, aesh and groovy are 'ok' 
the plan is to remove groovy to save +-4.5mb
but for html/js/css and servlet we don't need security (not now) and others stuff got it ?
this was the main discussion

**Comment by kenfinnigan** [comment]
@eprogramming Have you tried excluding the swarm-security dependency from swarm-jaxrs?

Given this is a closed issue, it's probably worth starting a new one to discuss this, so it can easily be found

**Comment by eprogramming** [comment]
> Have you tried excluding the swarm-security dependency from swarm-jaxrs?

no , how i can do this ?

> Given this is a closed issue, it's probably worth starting a new one to discuss this, so it can easily be found

+1 thanks @kenfinnigan

**Comment by kenfinnigan** [comment]
<dependency>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>wildfly-swarm-jaxrs</artifactId>
      <version>${version.wildfly-swarm}</version>
      <exclusions>
        <exclusion>
          <groupId>org.wildfly.swarm</groupId>
          <artifactId>wildfly-swarm-security</artifactId>
        </exclusion>
      </exclusions>
    </dependency>

**Comment by bobmcwhirter** [comment]
see also

https://github.com/wildfly-swarm/wildfly-swarm/issues/62

and example of static-content-in-war and <packaging>war</packaging> 

https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/master/static-war
