### ISSUE TITLE
Missing favicon.ico produces verbose exception in logs

### ISSUE THREAD

**Issue by kenfinnigan** [wildfly-swarm/wildfly-swarm#22]
When running the JAX-RS examples, there is a very verbose exception logged when favicon.ico can not be found.

Not sure if it's particular to RESTeasy or Undertow, but might be worth trying to work around in WildFly Swarm

**Comment by bobmcwhirter** [comment]
If an app provides a favicon.ico via static files, it should serve.

If they magically serve one through JAXRS, it should serve.

If ultimately JAXRS throws a NotFoundException, and it's for favicon.ico, we will serve up the WildFly favicon.ico.

Not really a feature, but should silence some of the console stack-trace WARN entries.

**Comment by bobmcwhirter** [comment]
@nmcl see above.
