### ISSUE TITLE
Update samples to Java EE 7

### ISSUE THREAD

**Issue by kenfinnigan** [wildfly-swarm/wildfly-swarm#24]
_From @arun-gupta on May 6, 2015 16:32_

Code samples should be updated to Java EE 7.

Particularly https://github.com/wildfly-swarm/example-jaxrs/blob/master/src/main/webapp/WEB-INF/web.xml is not even needed. Or should look something like https://github.com/javaee-samples/javaee7-samples/blob/master/servlet/metadata-complete/src/main/webapp/WEB-INF/web.xml.

Note the namespaces are different.

I suspect other samples are using a similar `web.xml`.

_Copied from original issue: wildfly-swarm/example-jaxrs#1_

**Comment by bobmcwhirter** [comment]
@arun-gupta would you mind knocking this one out, if it's still applicable?

**Comment by arun-gupta** [comment]
Sure, will look at it. Moving all of them together in https://github.com/wildfly-swarm/examples certainly makes it easier.

**Comment by arun-gupta** [comment]
@bobmcwhirter it would be good to rename examples to wildfly-swarm-examples so that the workspace can be easily identified when checked out?

**Comment by arun-gupta** [comment]
3e423cec49617164e88628f0c3fd28c696a8c775 fixed this issue.
