### ISSUE TITLE
Missing exports from Transaction Fraction

### ISSUE THREAD

**Issue by nmcl** [wildfly-swarm/wildfly-swarm#27]
Presumably just as the JMS one exports the JMS API, so should this one export JTA , i.e., 

<export>javax.transaction</export>

**Comment by bobmcwhirter** [comment]
Probably exactly. Thanks!

--

**Comment by nmcl** [comment]
Meant to say that at least for now I'm able to work around this by including the following in my example builds ...

<dependency>
	<groupId>javax.transaction</groupId>
	<artifactId>jta</artifactId>
	<version>1.1</version>
      </dependency>
