### ISSUE TITLE
Transaction example

### ISSUE THREAD

**Issue by nmcl** [wildfly-swarm/wildfly-swarm#28]
I've created a basic transaction example and will continue to update it. Not sure if you want to include it within the main repo or link to it - I'm happy to do either.

https://github.com/nmcl/wfswarm-example-transactions

**Comment by bobmcwhirter** [comment]
Awesome! Definitely want to pull examples under our organization to keep them all handy and up-to-date. 

I'll grant you privs tomorrow. 

--

**Comment by kenfinnigan** [comment]
Closing, as the example has been migrated to this organization
