### ISSUE TITLE
Netflix OSS Support

### ISSUE THREAD

**Issue by lance** [wildfly-swarm/wildfly-swarm#29]
Netflix OSS provides powerful open source tools that would be very nice additions to WF Swarm. These tools can enable services and patterns like Service Discoverability, Client Side Load Balancing, and Circuit Breaker. Because Netflix assumes an AWS infrastructure for at least one of these services, we will need to either find a replacement or fork/modify the Netflix offerings. 

The Netflix tools for these capabilities are:

* Service Discoverability: Eureka. This service assumes an AWS cloud infrastructure, but is runnable locally on a developer machine.
* Client Side Load Balancing: Ribbon. No obvious AWS dependencies
* Circuit Breaker: Hystrix. No obvious AWS dependencies

Swarm should make these patterns available to developers in a simple and declarative way through annotations which can selectively activate the service. An example of how this would work with Service Discovery is shown with a pseudo code example below.

## Service Discovery
Keep in mind that Eureka clients will need a full-fledged Eureka server to talk to.

    // Registers this service with the Eureka server 
    // and makes this class also a Eureka client
    @DiscoveryEnabled
    public class TimeService extends HttpServlet {

        @Inject
        private DiscoveryClient client;

        @Override
        protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
            resp.getWriter().write( new DateTime() );
        }

        // if this made up service relied on some other service, like
        // a TACOS service, the Eureka server will provide the next server available
        private String tacosURL() {
            InstanceInfo instance = client.getNextServerFromEureka("TACOS", false);
            return instance.getHomePageUrl();
        }
    }

**Comment by emag** [comment]
+1 !

**Comment by kenfinnigan** [comment]
Would something like this be for WildFly Swarm, which is mostly concerned with fat jar'ing WildFly pieces, or would it be suited to something that would utilize WildFly Swarm as a deployment structure but is itself a separate project?

For example, this is an area I've been thinking of shifting LiveOak towards, being a microservice container with discovery, etc

**Comment by burrsutter** [comment]
From my end-user perspective, the discovery piece is the "easy" part, having load-balancing & circuit-break (and other services) with async invocations, all with a super simple annotation-based packaging is the more interesting part.  
@kenfinnigan I agree that there are aspects of LiveOak that could be valuable here as well - as REST would be the default communication model between services

**Comment by lance** [comment]
@kenfinnigan no, I don't think this has to be swarm specific. I think these would be components that we should be able to use elsewhere for sure. But I keep hearing about it in regards to Swarm (I'm looking at you, @burrsutter), so this just seemed like the most convenient place to get the conversation started. Perhaps it is another project entirely.

With regard to easy vs. hard, I think all of this is complex but no one piece stands out as necessarily more difficult than the other. Below is my example expanded a little to show how the circuit breaker patter could be implemented using hystrix. Again, pseudocode. Not much here is real.  One thing I haven't considered is async invocation. That's probably a whole 'nother ball of wax.

    // Registers this service with the Eureka server
    // and makes this class also a Eureka client.
    // Enable circuit breaker capabilities
    @DiscoveryEnabled
    @CircuitsEnabled
    public class FrontAPIService extends HttpServlet {

        @Inject
        private DiscoveryClient client;

        @Override
        protected void doGet(HttpServletRequest req, HttpServletResponse resp) throws ServletException, IOException {
            resp.getWriter().write( getDateTime() );
        }

        // This call may fail, take too long, or otherwise be unavailable.
        // Making it circuited prevents a failure from propagating to the client
        @CircuitedCommand( fallback = "fallbackDateTime")
        private Object getDateTime() {
            InstanceInfo instance = client.getNextServerFromEureka("DATETIME", false);
            String url =  instance.getHomePageUrl();
            Object result;
            // fetch the the DateTime from our server instance and return
            // it. This will take time and could fail, so be sure we are
            // Circuited and have a fallback
            return result;
        }
    
        private Object fallbackDateTime() {
            return new Date();
        }
    }

**Comment by bobmcwhirter** [comment]
Haven't addressed anything, really, but have verified that Ribbon at least, works within Swarm.

https://github.com/wildfly-swarm/wildfly-swarm-examples/blob/master/multiple/events/src/main/java/org/wildfly/swarm/examples/multi/events/EventsResource.java

When pulling in Eureka, though, there's some issues in conflicts with RESTEasy, I think, when Undertow tries to initialize servlets and parts of com.sun.jersey are missing.

I'd like to investigate WildFly-clustering based solution for service discovery, mayhap.

**Comment by heiko-braun** [comment]
IMO service discovery shouldn't be tight to a specific impl. It would be good to support other registries like: zookeeper, consul, etcd

**Comment by heiko-braun** [comment]
@bobmcwhirter 

> I'd like to investigate WildFly-clustering based solution for service discovery, mayhap.

you mean a registry inetgrated with swarm?

**Comment by bobmcwhirter** [comment]
Yah right now it's based on JGroups and WF clustering but certainly can be more generalized. And should be for OpenShift etc. 

--

**Comment by bobmcwhirter** [comment]
Closing.  Further features should be new issues.
