### ISSUE TITLE
Quick Start with a maven plugin

### ISSUE THREAD

**Issue by gdrouet** [wildfly-swarm/wildfly-swarm#3]
Hi,

Do you plan to provide a maven plugin that generates a default main class if not exist and launch it with a single command line? This would be helpful to create lot of samples based on any wildfly components. What do you think?

**Comment by kenfinnigan** [comment]
If an Project that uses WildFly Swarm doesn't specify it's own Main class, then https://github.com/wildfly-swarm/wildfly-swarm/blob/master/container/src/main/java/org/wildfly/swarm/container/DefaultMain.java is used by default.

Is there something more than that requirement you were looking for?

**Comment by gdrouet** [comment]
Yes, the goal that runs the main class once packaging is done :-) maybe this already exist?

**Comment by kenfinnigan** [comment]
You want to be able to execute the main class as part of the Maven plugin that packages it?

Currently once packaging is complete, you simply run 'java -jar myJar.jar' to execute.

**Comment by bobmcwhirter** [comment]
Basically the maven-exec-plugin could handle it.

We could create a Mojo that wraps/extends it with the appropriate arguments to make it even easier to execute the just-created jar.

	-Bob

**Comment by gdrouet** [comment]
That's it. A dedicated mojo could reduce boilerplates with maven exec plugin. The mojo could also expose some parameters to customize the default main class. This kind of API could be more userfriendly in some cases rather than writing a .java with a main method.

**Comment by bobmcwhirter** [comment]
Just to clarify, I think we’re talking about two separate points:

a) Modifications to the ‘create' mojo to generate a MainClass (but you’d still need to muck about with the maven-jar-plugin mainClass config directly) with some parameters.

b) A new ‘run’ mojo to simplify the maven-exec-plugin

The main-class portion happens at build time, not execution time, other than defaulting to the -swarm’s own DefaultMain if none is specified in the MANIFEST.MF

**Comment by gdrouet** [comment]
+1! I think those enhancements bring more value to -swarm, what do you think? I can send a PR if you think this is in -swarm's scope

**Comment by bobmcwhirter** [comment]
Certainly!

All PRs are welcomed and will be reviewed and more than likely merged.

Thanks!

**Comment by agoncal** [comment]
BTW, Spring Boot has this sort of behaviour where you can either execute a jar with `java -jar my.jar`, or use the plugin `mvn spring-boot:run`. 

A `mvn swarm:run` would be nice

**Comment by bobmcwhirter** [comment]
@gdrouet Are you actively working on this?  If not, I'll work on creating a RunMojo today.  But I don't want to trample your toes if you've got something in the works.

**Comment by gdrouet** [comment]
Sorry I won't have the time to work on this before 1/2 weeks, just designed in my head atm :-)

You can work on it now!

**Comment by bobmcwhirter** [comment]
Okie dokie, thanks!

**Comment by gdrouet** [comment]
BTW as you can imagine I'm really interested in this feature, if you can cut a release once you have something to test then I'll have a concrete use case to share ;-)

**Comment by bobmcwhirter** [comment]
I imagine we'll be cutting Alpha releases pretty quickly in the near term, as folks have found issues and we're making improvements quickly.  We'll definitely let you know when we do.

**Comment by kenfinnigan** [comment]
Please reopen if this is not resolved
