### ISSUE TITLE
How is the web context set in undertow ?

### ISSUE THREAD

**Issue by agoncal** [wildfly-swarm/wildfly-swarm#31]
Hi all,

I'm playing with JBoss Forge and the Swarm-addon for Forge. Basically, this addon just sets up the Swarm dependency in the `pom.xml`, and it works quite well actually. 

So, when I create a basic REST endpoint with Forge I'd go : 

```
$ project-new --named test
$ rest-new-endpoint --named MyEndpoint --methods GET 
```

This creates a `test.war` file, I package it, deploy it to Wildfly, and I can ping my endpoint pointing at `http://localhost:8080/test/rest/myEnpoint`. Then, I setup Swarm

```
$ wildfly-swarm-setup
```

I can now execute the Fatjar and ping my endpoint at `http://localhost:8080/rest/myEnpoint`.

The good thing is that I can quickly create a Swarm project with Forge in only 3 lines of code. The problem, is that the web context differs from one to the other. This is what I get when deploying the war to WildFly :

```
INFO  [org.wildfly.extension.undertow] (MSC service thread 1-3) WFLYUT0021: Registered web context: /test
```
This is what I get when executing the Fatjar : 
```
INFO  [org.wildfly.extension.undertow] (MSC service thread 1-16) WFLYUT0021: Registered web context: /
```

The root context cannot be set in `web.xml` (there is none in the project anyway) and should be set in a higher descriptor (eg. `application.xml`) or other descriptor (eg. `jboss-web.xml`, `jboss-deployment-structure.xml`). But because there is none, I assume that Undertow creates one when a war is deployed (based on the name of the war) but doesn't when executed with Swarm.

Is there a way to have the same root context in both cases (deployed in WildFly and executed with Swarm) ? Or how could I have a `test` web root context in Swarm ?

**Comment by emag** [comment]
You can add your own jboss-web.xm if you package your app as warl.

``` xml
<?xml version="1.0" encoding="UTF-8"?>
<jboss-web>
  <context-root>/test</context-root>
</jboss-web>
```
But, in the case of `jar` packaging for some fraction settings, I don't know how to change it.

## reference

https://github.com/wildfly-swarm/example-jaxrs#use

**Comment by bobmcwhirter** [comment]
The runtime adds a jboss-web.xml if there isn't one in your app already. Perhaps we should make it optional or configurable. 

--

**Comment by agoncal** [comment]
And what about being able to customize the context root in the Swarm plugin, (such as the Maven [ear plugin](https://maven.apache.org/plugins/maven-ear-plugin/examples/customizing-context-root.html)). Something like : 

```
<plugin>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-plugin</artifactId>
  <version>${version.wildfly-swarm}</version>
  <executions>
    <execution>
      <phase>package</phase>
      <goals>
        <goal>create</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <contextRoot>/test</contextRoot>
  </configuration>
</plugin>
```

**Comment by kenfinnigan** [comment]
We can certainly provide ways to customize what the context is, but I'm curious as to the benefit?

Given WildFly Swarm is single deployment, what are the benefits of being able to set the context root to something other than '/' ?

**Comment by agoncal** [comment]
You can see it as another way of differentiating services. If I need to have several microservices running on the same machine, I need to change port numbers, REST endpoints, servlets.... but why not also being able to change the context root ? 

In the example I'm giving with Forge, it's a nice way to show that deploying the war or running the fatjar is identical : same root context, same services....

**Comment by bobmcwhirter** [comment]
For services all within a jar that makes sense. Across multiple ones though, you have to have non-conflicting ports anyhow, no?

--

**Comment by agoncal** [comment]
Yes, conflicting port is an issue for sure. BTW, can the port number be configured in the Swarm plugin like the [JBoss plugin](http://docs.jboss.org/jbossas/7/plugins/maven/latest/examples/run-example.html) ? 

````
<plugin>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-plugin</artifactId>
  <version>${version.wildfly-swarm}</version>
  <executions>
    <execution>
      <phase>package</phase>
      <goals>
        <goal>create</goal>
      </goals>
    </execution>
  </executions>
  <configuration>
    <port>7777</port>
    <contextRoot>/test</contextRoot>
  </configuration>
</plugin>
```

**Comment by bobmcwhirter** [comment]
Defaults to 8080 and with fatjar can be controlled with the property jboss.bind.port to override. 

Adding to the config might be useful. Especially for wildfly-swarm:run plugin. 

Would you mind filing an issue for this feature?

--

**Comment by agoncal** [comment]
Done

**Comment by agoncal** [comment]
And what about configuring the context root ? Do you want me to create an issue or you forget about it now ?

**Comment by bobmcwhirter** [comment]
I think this issue is good for tracking that. 

--

**Comment by bobmcwhirter** [comment]
See the commit message for that to understand the details, please.
