### ISSUE TITLE
Websocket Support

### ISSUE THREAD

**Issue by amannm** [wildfly-swarm/wildfly-swarm#34]
I'm currently making websocket microservices using a "fork" of Wildfly Swarm where the only difference is the addition of this dependency to the `wildfly-swarm-undertow` module's `pom.xml`
<pre>
        &lt;dependency&gt;
            &lt;groupId&gt;org.jboss.spec.javax.websocket&lt;/groupId&gt;
            &lt;artifactId&gt;jboss-websocket-api_1.1_spec&lt;/artifactId&gt;
        &lt;/dependency&gt;
</pre>
and with this new version I probably now also need to add a line to the module's `/src/resources/provided-dependencies.txt`
<pre>
org.jboss.spec.javax.websocket:jboss-websocket-api_1.1_spec
</pre>

I'm not sure if piggybacking on `wildfly-swarm-undertow` like this is the correct way or if this is something that needs a separate new module/fraction/whatever (`wildfly-swarm-undertow-websocket`?) but it would definitely be helpful to have some sort of official feature for those of us that require websockets

**Comment by bobmcwhirter** [comment]
I think we should merge that into core. Thanks!

--

**Comment by bobmcwhirter** [comment]
I've added these changes to HEAD of wildfly-swarm, if you could verify it works for you.

**Comment by amannm** [comment]
Look's like it's working great. Thanks!
