### ISSUE TITLE
Not able to generate fat jar with JPA module

### ISSUE THREAD

**Issue by arun-gupta** [wildfly-swarm/wildfly-swarm#35]
Created a sample that uses JAX-RS and JPA together at https://github.com/arun-gupta/wildfly-samples/tree/master/swarm. Packaging the fat jar using `mvn package` gives the following error:

```
[ERROR] Failed to execute goal org.wildfly.swarm:wildfly-swarm-plugin:1.0.0.Alpha2-SNAPSHOT:create (default) on project swarm: Failed to analyze module XML for /Users/arungupta/workspaces/wildfly-samples/swarm/target/wildfly-swarm-archive/modules -> [Help 1]
```

Seems like a its looking for `modules` directory?

**Comment by bobmcwhirter** [comment]
That is intensely weird. Try removing the target/ dir and do a fresh build?

I'll look tomorrow. 

--

**Comment by arun-gupta** [comment]
I always try `'mvn clean package`, and confirming again that's what I tried.

**Comment by bobmcwhirter** [comment]
Can you mvn with -e and gist the full stack?

--

**Comment by kenfinnigan** [comment]
@arun-gupta right now, the project needs to package as `jar` and not `war`, and you will need some kind of Main class, as in the cdi-servlet example, to deploy the driver, datasource and the app itself

**Comment by arun-gupta** [comment]
https://gist.github.com/arun-gupta/4964ffd06217757425dd

**Comment by arun-gupta** [comment]
@kenfinnigan ah, that might be the case, let me try that. When is the WAR support coming?

**Comment by emag** [comment]
@kenfinnigan  @arun-gupta 
I got the error on my sample. It seems wildfly-swarm-plugin configuration setting(execution) has changed.
I changed it and it works.

See https://github.com/wildfly-swarm/example-jpa-servlet/blob/master/pom.xml#L50-L56

**Comment by kenfinnigan** [comment]
@arun-gupta I've created #36 to track WAR support

**Comment by arun-gupta** [comment]
@emag This would still require to create a Main file though which is what I was missing. Right?

**Comment by kenfinnigan** [comment]
Yes, at the moment we need a Main to deploy everything

**Comment by emag** [comment]
@arun-gupta Oh, sorry. I just checked my simple jax-rs sample(alomost same swarm-example, no jpa).

https://github.com/emag/wildfly-swarm-quickstarts/blob/master/jaxrs/pom.xml#L19-L26

And, using jpa must prepare datasource, driver, so you need to setup these in your Main.

**Comment by bobmcwhirter** [comment]
You may be able to put a -ds.xml in your war along with the db driver jar in the WEB-INF/lib dir. WildFly is pretty handy at finding drivers. But I could be wrong. 

--

**Comment by kenfinnigan** [comment]
I might change the current example to being shrinkwrap and look to make an example in the way @bobmcwhirter  suggested

**Comment by arun-gupta** [comment]
@kenfinnigan that would certainly simplify, lets leverage all the simplifications :)

You also might be able to leverage `deployment.getArchive().addPackage(Main.class.getPackage());` instead of manually adding all classes.

**Comment by arun-gupta** [comment]
Two JAR files are generated in the `target` directory:

```
-rw-r--r--   1 arungupta  staff  90826160 May 28 18:10 swarm-1.0-SNAPSHOT-swarm.jar
-rw-r--r--   1 arungupta  staff      6286 May 28 18:08 swarm-1.0-SNAPSHOT.jar
```
This is confusing!

**Comment by bobmcwhirter** [comment]
One is your normal jar artifact created by maven. The other is the fatjar wrapping it created by swarm plugin. 

Dunno what we could do elsewise. 

--

**Comment by arun-gupta** [comment]
Hmm, ideally the fat jar should be the only one located in this directory otherwise it could lead to confusing error messages as:

```
swarm> java -jar target/swarm-1.0-SNAPSHOT.jar 
no main manifest attribute, in target/swarm-1.0-SNAPSHOT.jar
```

Or possibly use `swarm' at the beginning of the JAR file name?

**Comment by bobmcwhirter** [comment]
That sorta breaks the maven way though. The -swarm suffix as a classifier is the normal behavior for maveny stuff. 

Is suffix not as good as a prefix?

--

**Comment by arun-gupta** [comment]
Lets stick with the current convention and see if anybody else complains about it, OK?

**Comment by kenfinnigan** [comment]
Closing this as I think we have issues covering some of the discussion mentioned above, but the reason for this issue is no longer a problem.

Feel free to reopen if that's not the case
