### ISSUE TITLE
Discussion on aggregating WildFly Swarm examples

### ISSUE THREAD

**Issue by emag** [wildfly-swarm/wildfly-swarm#40]
Although WildFly Swarm examples are very  helpful, it's difficult to check due to having its own repository.

How about aggregating such as [WildFly Quickstart](https://github.com/wildfly/quickstart) ?
(it'll be easy to  catch up with WildFly Swarm update)

**Comment by smiklosovic** [comment]
+1, and delete all other repositories which will be already in quickstart repo.

**Comment by kenfinnigan** [comment]
It's something we've been thinking about with the growing number of examples, but a decision hasn't been made as of yet

**Comment by kenfinnigan** [comment]
Done. https://github.com/wildfly-swarm/examples

**Comment by emag** [comment]
Cool!
