### ISSUE TITLE
JPA sample and QueryDSL fires java.lang.LinkageError

### ISSUE THREAD

**Issue by turisto** [wildfly-swarm/wildfly-swarm#43]
Hi, a question here :)

I am playing with Alpha2 snapshot + jpa + jax-rs sample (https://github.com/wildfly-swarm/example-jpa-jaxrs-cdi) and trying to go further with QueryDSL (https://github.com/aracrown/ara-blog-examples/tree/master/s01e04) example. However, when trying to call a WS I get  java.lang.LinkageError: javax/persistence/EntityManager (https://gist.github.com/turisto/7d140b4fb9fa510f0ed5).

Currently I going with jar + Main configuration. Do I need to add something specific into Main class container or deployment? I believe it is related to configuration issues :)

Best regards,
Vytas

**Comment by kenfinnigan** [comment]
Do you have the JPA API as a dependency to your project? Or does QueryDSL include it?

**Comment by turisto** [comment]
My project does not have this dep as it is currently clone of example-jpa-jaxrs-cdi. QueryDSL has "provided" dependency of JPA API (<scope>provided</scope>).

**Comment by kenfinnigan** [comment]
Hmm, had a quick play with your example and wasn't able to see where the Classloading issue is coming from. Need to dig deeper.

**Comment by bobmcwhirter** [comment]
Howdy, just fixed this in HEAD of wildfly-swarm.

One change required for your application is adding this line to your `main()`

```
        deployment.getArchive().addClasses(QEmployee.class);
```

Then it should work appropriately.

**Comment by turisto** [comment]
Cool. It works now! :)
