### ISSUE TITLE
Project website

### ISSUE THREAD

**Issue by kenfinnigan** [wildfly-swarm/wildfly-swarm#44]
Basic website with some initial docs, particularly on creating a fraction for a WildFly subsystem

**Comment by hwellmann** [comment]
Some questions to be covered by the docs:
* Why is a fat JAR a good idea at all? 
* What are the typical use cases, and when would you better stick with traditional containers and deployments?
* How do you deal with target-specific settings like data source URLs or JMS queues? If these are all compiled into the fat JAR, then this JAR will work on exactly one target host.

**Comment by agoncal** [comment]
A FAQ is always a good idea so developers understand better where they are : 

* How is Swarm related to Wildfly ?
* What is a micro service ?
* Is Swarm a micro service container ?
* Is JBoss AS a fat service container ?
* And what about Docker ?
* What is a fat jar ?
* What about standardizing the "fatjar" structure (like war/ear) ?
* Can I deploy a "fatjar" in JBoss ?
... (more to come)

**Comment by emag** [comment]
* How can I test it ?
 * I suggest using [Arquillian Cube(Containerless container)](https://github.com/aslakknutsen/cube-wildfly-swarm).

**Comment by bobmcwhirter** [comment]
Do you have any examples to share? I suck at testing. Obviously. 

--

**Comment by emag** [comment]
@bobmcwhirter Oh, I mean `test(especiaaly integration, functional test)` is for an application using WildFly Swarm, not WildFly Swarm self.

Though Arquillian Cube need to use Docer, it's  helpful.

So far I have no idea for WildFly Swarm, I will share you if I think of good ideas.

**Comment by bobmcwhirter** [comment]
Yep. If we did that against out examples that'd be useful examples of testing for others and give us some testing for swarm itself. 

--

**Comment by eprogramming** [comment]
@agoncal +1
good questions.

**Comment by eprogramming** [comment]
And +1 to keep jar and war only ( KISS )

**Comment by bobmcwhirter** [comment]
Discussing hoisting up from wildfly.org/swarm to its own top-level domain.

Mostly blog, but possibly FAQ and other non-bloggy things.

**Comment by jclingan** [comment]
Being a newbie, what is the right way for us to do this? I'd like to start pointing developers "somewhere" besides what we have now.  Of course, I'll help generate content too.

**Comment by bobmcwhirter** [comment]
We need to get Lance home from NYC to get it set up. You can start writing
content in asciidoc though and I'll make a repo for it later today or
tomorrow. Or maybe Friday. Or maybe Ken will.

We have domains now. Yay.

--
Sent from my iPhone


On Nov 4, 2015, at 1:46 PM, John Clingan <notifications@github.com> wrote:

Being a newbie, what is the right way for us to do this? I'd like to start
pointing developers "somewhere" besides what we have now. Of course, I'll
help generate content too.

—
Reply to this email directly or view it on GitHub
<https://github.com/wildfly-swarm/wildfly-swarm/issues/44#issuecomment-153826820>
.

**Comment by lance** [comment]
I will be back tomorrow (after sleeping in a little), and will get that
ball rolling.

On Wednesday, November 4, 2015, Bob McWhirter <notifications@github.com>
wrote:

> We need to get Lance home from NYC to get it set up. You can start writing
> content in asciidoc though and I'll make a repo for it later today or
> tomorrow. Or maybe Friday. Or maybe Ken will.
>
> We have domains now. Yay.
>
> --
> Sent from my iPhone
>
>
> On Nov 4, 2015, at 1:46 PM, John Clingan <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
>
> Being a newbie, what is the right way for us to do this? I'd like to start
> pointing developers "somewhere" besides what we have now. Of course, I'll
> help generate content too.
>
> —
> Reply to this email directly or view it on GitHub
> <
> https://github.com/wildfly-swarm/wildfly-swarm/issues/44#issuecomment-153826820
> >
> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/wildfly-swarm/wildfly-swarm/issues/44#issuecomment-153827908>
> .
>


-- 
Lance Ball
http://lanceball.com

**Comment by jclingan** [comment]
OK, you guys are moving way faster than I am :-)

Humph, just when I was getting Markdown down, now I have to pick up asciidoc :-) #LearnAsYouGo

**Comment by bobmcwhirter** [comment]
Here's a repo:

https://github.com/wildfly-swarm/wildfly-swarm.io

@jclingan for AsciiDoc, I like this http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/

And also our docs are written in AsciiDoc if you like to learn-by-example: https://github.com/wildfly-swarm/wildfly-swarm-users-guide

**Comment by lance** [comment]
Basic site is now up at https://wildfly-swarm.io. You can write documents in either Markdown or AsciiDoc. If there's another format that's preferred, just let me know and I can add it. 

There is not a lot of content on the site at the moment. Should we keep this issue open until it's fully fleshed out? Or just start adding individual issues like "There should be an FAQ on the website"?

**Comment by jclingan** [comment]
> On Nov 10, 2015, at 11:24 AM, Lance Ball <notifications@github.com> wrote:
> 
> Basic site is now up at https://wildfly-swarm.io <https://wildfly-swarm.io/>. You can write documents in either Markdown or AsciiDoc. If there's another format that's preferred, just let me know and I can add it.
> 
> There is not a lot of content on the site at the moment. Should we keep this issue open until it's fully fleshed out? Or just start adding individual issues like "There should be an FAQ on the website"?
> 
> 
Close the issue. I’ll get around to beefing up content. Pretty high on my priority list because we need a place to point to. Pointing developers straight to github project is like pointing someone looking for directions to the architectural designs of the destination :-)
