### ISSUE TITLE
Conference Driven Development

### ISSUE THREAD

**Issue by agoncal** [wildfly-swarm/wildfly-swarm#45]
Hi guys,

I'm giving a one hour talk on JBoss Forge at DevoxxUK in a couple of weeks. I'll be using the Swarm addon... and I'm wondering if an Alpha2 will be available before the conference ;o)

**Comment by bobmcwhirter** [comment]
Hopefully in the next 24 hours. 

--

**Comment by agoncal** [comment]
You guys rock !!!

**Comment by kenfinnigan** [comment]
It would be happening now if I had internet where i am right now, but definitely later

**Comment by agoncal** [comment]
@kenfinnigan The beauty of Git is to be offline ;o)

**Comment by bobmcwhirter** [comment]
@agoncal but the "beauty" of a maven release is that you have to be online. :)

**Comment by agoncal** [comment]
@bobmcwhirter Life is not perfect !

**Comment by kenfinnigan** [comment]
@agoncal forgot to respond last night that Alpha2 is now out in the wild!

**Comment by agoncal** [comment]
Guys, I'm working on the Swarm Forge addon to introduce the Swarm plugin configuration (httpPort, contextPath....). Do you know if the Alpha3 will be released soon (I'm still thinking of my talk at Devoxx UK next Thursday ;o) ?

Thanks

**Comment by bobmcwhirter** [comment]
Yah, I think we can try to get alpha3 out before then.

The plugin config and static improvements would be worth it.

Release early, often and vigorously!

**Comment by agoncal** [comment]
Great !!!!

Just to let you know that the JBoss Forge addon is up and running... just waiting for the Alpha3 ;o)

https://github.com/forge/wildfly-swarm-addon/pull/7#issuecomment-111567142

**Comment by agoncal** [comment]
Any news on the Alpha3 ? If it is out soon I could update the Forge addon to use it. Let me know if it is released before DevoxxUK (tomorrow ;o)

**Comment by kenfinnigan** [comment]
Probably released tomorrow US time, not sure if that's soon enough
