### ISSUE TITLE
Allow reintroduction of missing Sun JDK classes

### ISSUE THREAD

**Issue by amannm** [wildfly-swarm/wildfly-swarm#50]
I'm unable to use the [dnsjava library](http://sourceforge.net/projects/dnsjava/) in Wildfly Swarm projects due to its internal use of `sun.net.dns.ResolverConfguration`
<pre>
String resConfName = "sun.net.dns.ResolverConfiguration";
Class resConfClass = Class.forName(resConfName);
</pre>
<pre>
java.lang.ClassNotFoundException: sun.net.dns.ResolverConfiguration from [Module "deployment.5d957258-9f2c-408f-9934-ca814f328afb.war:main" from Service Module Loader]
</pre>

I think this is because [JBoss AS7 excludes certain JDK classes](https://docs.jboss.org/author/display/AS71/Class+Loading+in+AS7) by default. There's a decent amount of posts out there [explaining how to add them back in by modifying some configuration files](https://javaspecialist.wordpress.com/2014/12/13/dealing-with-sun-jdk-related-noclassdeffounderror-under-jboss/) for JBoss AS7, but I'm unclear on how to get this done with Wildfly Swarm.

If these Sun JDK classes are being excluded for a reason worth the inconvenience of not having things *just work* on this platform, then users should be exposed some sort of configuration parameter to manually add them back in.

**Comment by kenfinnigan** [comment]
Can you provide a small example project utilizing the dnsjava library that encounters this problem?

The solution provided in https://github.com/wildfly-swarm/wildfly-swarm/pull/51 may not be the best long term approach to providing access to internal JDK classes, but I've been unable to replicate the issue you're having with an example.

**Comment by amannm** [comment]
Here's an example project which currently suffers from this issue.on my machine: https://github.com/amannm/wildfly-swarm-example please comment the `org.ow2.asm` dependency in pom.xml back in and comment back in the `DnsLookup.getSearchSuffixes();` in `Application.java`

**Comment by emag** [comment]
@amannm I tested your example(enable org.ow2.asm:asm in pom.xml) and no ClassNotFoundException or other error.

My environment:

* OS: Fedora 21
* JDK: openjdk version "1.8.0_45"
* WildFly-Swarm: HEAD(cb141bc)

I displayed [defaultSearchPaths](https://github.com/amannm/wildfly-swarm-example/blob/master/src/main/java/com/amannmalik/service/example/Application.java#L20) and got `[stdout] (main) [Lorg.xbill.DNS.Name;@50a638b5` .

**Comment by emag** [comment]
Sorry, I misunderstood and I can reproduce by disabling org.ow2.asm:asm dependency.
(https://github.com/wildfly-swarm/wildfly-swarm/issues/52).

**Comment by emag** [comment]
I switch wildfly-swarm-weld-jaxrs scope to `compile` and no ClassNotFoundException.

**Comment by amannm** [comment]
Ok that's it then, apparently I was using the outdated method of using `provided` scope and it was manifesting itself as these issues. Thanks
