### ISSUE TITLE
how excluding some dependency ?

### ISSUE THREAD

**Issue by eprogramming** [wildfly-swarm/wildfly-swarm#58]

**Comment by eprogramming** [comment]
https://github.com/wildfly-swarm/wildfly-swarm/issues/21#issuecomment-112981989

**Comment by kenfinnigan** [comment]
<dependency>
  <groupId>org.wildfly.swarm</groupId>
  <artifactId>wildfly-swarm-jaxrs</artifactId>
  <version>${version.wildfly-swarm}</version>
  <exclusions>
    <exclusion>
      <groupId>org.wildfly.swarm</groupId>
      <artifactId>wildfly-swarm-security</artifactId>
    </exclusion>
  </exclusions>
</dependency>

**Comment by eprogramming** [comment]
thanks a lot and going to try this right now !
the subject is ( we all know how to exclude using maven, the trick is ' is safe/good to exclude' if yes: how ? )

1 min going to check this one

**Comment by eprogramming** [comment]
**before:**

![a](https://cloud.githubusercontent.com/assets/6443576/8221402/50fad720-1534-11e5-83ad-51636a2b290b.png)

**after:**

![b](https://cloud.githubusercontent.com/assets/6443576/8221413/933c6040-1534-11e5-88bf-2003ac0f9008.png)

weird...

going to delete .m2/ and all stuff

**Comment by bobmcwhirter** [comment]
mvn dependency:tree

Is also useful for figuring out what's in your build. 

--

**Comment by eprogramming** [comment]
what i do is:
1  update my fork with the latest
2 drop .m2/
3 mvn clean install and waiting.....
then try again

**Comment by bobmcwhirter** [comment]
Should not have to drop your .m2/

It's just a local cache really. It could be full of gigs of jars and not affect the final -swarm.jar size. 

--

**Comment by eprogramming** [comment]
@bobmcwhirter this is good feedback this will be the last one btw.
thanks.

**Comment by eprogramming** [comment]
hey this is important and ofc awesome :
https://github.com/wildfly-swarm/wildfly-swarm-presentations/raw/master/MSA%20Day%20-%20WildFly-swarm.pdf

> Allows Java EE components to become
independently deployable (micro) services
• Applications deploy with only the components needed

**Comment by eprogramming** [comment]
mvn dependency:tree

https://gist.github.com/eprogramming/5b07117873a9ef51534d

```
➜  target git:(master) ✗ ls -losht
total 34M
4.0K drwxr-xr-x. 4 hf 4.0K Jun 17 21:30 classes
4.0K drwxrwxr-x. 2 hf 4.0K Jun 17 21:30 test-classes
 34M -rw-r--r--. 1 hf  34M Jun 17 21:29 nanook-0.61-SNAPSHOT-swarm.jar
4.0K drwxr-xr-x. 9 hf 4.0K Jun 17 21:28 wildfly-swarm-archive
212K -rw-r--r--. 1 hf 211K Jun 17 21:28 nanook-0.61-SNAPSHOT.jar
4.0K drwxr-xr-x. 2 hf 4.0K Jun 17 21:28 maven-archiver
4.0K drwxr-xr-x. 3 hf 4.0K Jun 17 21:28 maven-status
4.0K drwxr-xr-x. 3 hf 4.0K Jun 17 21:28 generated-sources
```

**Comment by eprogramming** [comment]
https://github.com/aeshell/nanook/blob/master/pom.xml

**Comment by eprogramming** [comment]
weird o_0
before update my fork it was +-23mb
this from hipchat:

![a](https://cloud.githubusercontent.com/assets/6443576/8221857/0d4c76fe-153a-11e5-9a56-09fdb6064e3c.png)

**Comment by bobmcwhirter** [comment]
Websockets are part of undertow so we added the spec api jar to the build. We might could split it out into finer-grained bits to avoid pieces people don't need. 

--

**Comment by eprogramming** [comment]
@bobmcwhirter great !
thanks

**Comment by kenfinnigan** [comment]
It's all a question of how fine grained we go, given we'd also need to create combined versions so a users app doesn't need 6 dependencies to get something simple working.

It's a question of fraction proliferation over needing to exclude dependencies in app. It's a fine line and comes down to the most common use case

**Comment by bobmcwhirter** [comment]
Agreed. We need to analyze the marginal size additions and determine if it's worth breaking apart. 

--

**Comment by eprogramming** [comment]
@kenfinnigan +1 i totally agree !

a 'base wf-swarm' with the possibility of final-end-user customize the own app !

: ]

**Comment by eprogramming** [comment]
i have no problem with websockets btw ( in this case ) because this opens possibilities... but imagine if the apps really no need security ( i mean local usage to solve some problems )

**Comment by eprogramming** [comment]
> It's all a question of how fine grained we go,

delegate : ] ( to the end-user )

**Comment by eprogramming** [comment]
" \m/ https://www.youtube.com/watch?v=IjjCp_QU5Qk
let the DEVs choose the next song : p "

**Comment by kenfinnigan** [comment]
@eprogramming I think I lost track of what's happening with this. Does anything need to be done or can we close?

**Comment by eprogramming** [comment]
@kenfinnigan going to close because I need todo more tests thanks.
