### ISSUE TITLE
EJB Fraction

### ISSUE THREAD

**Issue by bobmcwhirter** [wildfly-swarm/wildfly-swarm#59]
Requested by @fbricon and probably others.

**Comment by eprogramming** [comment]
+1 request for this, we need to try EJB timer feature

**Comment by fbricon** [comment]
lack of EJB support forces us to manually handle transactions https://github.com/wildfly-swarm/wildfly-swarm-examples/compare/master...fbricon:kitchensink?expand=1#diff-a9991de129f5e3c3b1a36dbb75ae77c9R49

**Comment by emag** [comment]
@fbricon Yes, EJB is important. But as regarding transactions, you can use @ javax.transaction.Transactional. 

btw, your kitchensink migration is cool!

**Comment by bobmcwhirter** [comment]
You rock!

--

**Comment by eprogramming** [comment]
@kenfinnigan awesome !
EJB Timer working :
https://github.com/aeshell/nanook/commit/ace14a35afd8e3d7385cfa6799b06a575a497305
