### ISSUE TITLE
minor - getting some ansi on eclipse console

### ISSUE THREAD

**Issue by eprogramming** [wildfly-swarm/wildfly-swarm#60]
![a](https://cloud.githubusercontent.com/assets/6443576/8245976/1dcfd59c-160d-11e5-98d7-d182a63f4542.png)

**Comment by bobmcwhirter** [comment]
Ah. The default is color formatting. We can probably be smarter about TTY handling maybe. 

If you configure the LoggingFraction you can setup a simpler formatted without color. 

--

**Comment by emag** [comment]
@eprogramming 

Hmm, It's strange. In wf-swarm default logging setting, its named-formatter attr is [PATTERN](https://github.com/wildfly-swarm/wildfly-swarm/blob/master/runtime/logging/src/main/java/org/wildfly/swarm/runtime/logging/LoggingConfiguration.java#L37), not "COLOR-PATTERN".

Did you change it ?

Related entry
[Disabling color escape sequences in WildFly's console logging for IDE](http://www.nailedtothex.org/roller/kyle/entry/disabling-color-escape-sequences-in)

**Comment by eprogramming** [comment]
> If you configure the LoggingFraction you can setup a simpler formatted without color.

going to learn how to do it.

> Hmm, It's strange. In wf-swarm default logging setting, its named-formatter attr is PATTERN, not "COLOR-PATTERN".

got it, yup is a bit weird.

> Did you change it ?

No
[main class example](https://github.com/aeshell/nanook/blob/master/src/main/java/org/jboss/aesh/nanook/Main.java#L26)

**Comment by emag** [comment]
Ah, I'm with you. The color formatted log comes from boot logger whose formatter is "COLOR-PATTERN".

See WildFly Distribution logging.properties($WILDFLY_HOME/standalone/configuration/logging.properties).

If you change it, you need to overwrite it, maybe. Or, are there any way to do it?

**Comment by eprogramming** [comment]
@emag i got it, thanks
this right ? handler.CONSOLE.formatter=COLOR-PATTERN

and the blog entry was using 'named-formatter' maybe this is a 'custom handler attribute' ?
[wildscribe] (http://wildscribe.github.io/Wildfly/9.0.0.Beta1/subsystem/logging/custom-handler/index.html)

btw was good to learn how to configure LoggingFraction and ofc enable debug mode 
```
container.subsystem(new LoggingFraction()
.formatter("PATTERN", "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n")
.consoleHandler("DEBUG", "PATTERN")
.rootLogger("CONSOLE", "DEBUG"));
```
[logs](https://gist.github.com/eprogramming/4d2b38a8a598a9305570)

**Comment by emag** [comment]
@eprogramming 

> this right ? handler.CONSOLE.formatter=COLOR-PATTERN

Yes, exactly.

> and the blog entry was using 'named-formatter' maybe this is a 'custom handler attribute' ?

No, it's console-logger(and, it's runtime logger) attr. wildfly-swarm settings is 'PATTERN' while distro is 'COLOR-PATTERN' such like,

``` sh
[standalone@localhost:9990 /] /subsystem=logging/console-handler=CONSOLE:read-attribute(name=named-formatter)
{
    "outcome" => "success",
    "result" => "COLOR-PATTERN"
}
```

the blog guy uses WildFly distro.

> btw was good to learn how to configure LoggingFraction and ofc enable debug mode

Nice :) 

And you can use 'COLOR-PATTERN'. Of course, unfortunately, it's not Eclipse freindly...

``` java
...
.consoleHandler("DEBUG", "COLOR-PATTERN")
...
```

**Comment by emag** [comment]
@eprogramming 

I found a good plugin. I think you'd like it.

https://github.com/mihnita/ansi-econsole

My LoggignFraction setting is ...

``` java
container.subsystem(new LoggingFraction()
	.formatter("PATTERN", "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c] (%t) %s%e%n")
	.consoleHandler(DEFAULT_LEVEL, "COLOR-PATTERN")
	.rootLogger("CONSOLE", DEFAULT_LEVEL));
```
![screenshot from 2015-06-19 17 00 57](https://cloud.githubusercontent.com/assets/1188893/8249439/f6e64c20-16a4-11e5-9722-2a7cc975dd2f.png)

**Comment by eprogramming** [comment]
@emag yup i know this plugin before is good btw.

about the ansi escape code :

```
\u001B[0m
```
this means is only trying to reset 

so that, this is a issue from eclipse console not wildfly-swarm, and i guess this issue here can be closed : ]

**Comment by bobmcwhirter** [comment]
We've moved to the name COLOR_PATTERN and PATTERN for the color/ansi formatter and non-color, respectively.

It defaults to using COLOR_PATTERN, but we've also made it easier to change.
