### ISSUE TITLE
Bug - ShrinkWrap or WF-Swarm ?

### ISSUE THREAD

**Issue by eprogramming** [wildfly-swarm/wildfly-swarm#64]
Works from IDE (Eclipse) and *java -jar...*

```
getArchive().addClass(AeshHandler.class);
getArchive().addClass(NanookServlet.class);
```

Works from IDE (Eclipse) but **not** from *java -jar...* 
```
war.getArchive().addPackage("org.jboss.aesh.nanook");
```

[Stack here](https://gist.github.com/eprogramming/c5815f0af34e57d48f36)

**Comment by bobmcwhirter** [comment]
That's just weird. Got a repo I can muck with Monday?

--

**Comment by eprogramming** [comment]
https://github.com/aeshell/nanook

**Comment by bobmcwhirter** [comment]
So this is weird since we setup the SW domain within container and provide our own extension loader. 

I'll look on Monday but I imagine it's something simple. 

--

**Comment by eprogramming** [comment]
ok @bobmcwhirter thanks btw

**Comment by bobmcwhirter** [comment]
So I'd almost suggest trying without a main since your main uses default war and we might've fixed static stuffs. 

--
