### ISSUE TITLE
wildfly-swarm-ee not providing javax.enterprise.concurrent

### ISSUE THREAD

**Issue by amannm** [wildfly-swarm/wildfly-swarm#65]
The `wildfly-swarm-ee` fraction [confers support for the `javax.enterprise.concurrent` utilities](https://github.com/wildfly-swarm/wildfly-swarm/blob/master/runtime/ee/src/main/java/org/wildfly/swarm/runtime/ee/EEConfiguration.java) including `ManagedExecutorService` and `ManagedScheduledExecutorService`

However unlike other fractions, the pertinent Java EE APIs are not provided to users when they declare it as a dependency: [Example Project](https://github.com/amannm/wildfly-swarm-example)

**Comment by bobmcwhirter** [comment]
Merged the PR.
