### ISSUE TITLE
LogManager + groovy problem

### ISSUE THREAD

**Issue by eprogramming** [wildfly-swarm/wildfly-swarm#71]
Hi all,

Already tried:

```java
...
 static main(args) {
    System.properties.put('java.util.logging.manager','org.jboss.logmanager.LogManager')
...
```

```shell
export JAVA_OPTS="-Djava.util.logging.manager=org.jboss.logmanager.LogManager" 
```
but still not working.

I guess we need to point to log manager jar with bootclasspath to get this working but this is hard path coded.

*1) Have no idea if this is an issue related to wildfly-swarm.*

*2) Have no idea if it was an issue from groovy and is correct to open this issue here.*

example and stack error:
https://github.com/eprogramming/wildfly-swarm-gradle-groovy

**Comment by bobmcwhirter** [comment]
Does groovy use JUL?

If so, does it provide any hooks to initialize before its first use of JUL?

If so, check Container.java for how we bootstrap JUL for JBoss logging. 

--

**Comment by eprogramming** [comment]
@bobmcwhirter thanks for the tip !
this helped me to search for other solution:
@CompileStatic

**Comment by eprogramming** [comment]
working from IDE and  './executable'
https://github.com/eprogramming/wildfly-swarm-gradle-groovy
