### ISSUE TITLE
JAX-RS Async

### ISSUE THREAD

**Issue by bobmcwhirter** [wildfly-swarm/wildfly-swarm#73]

**Comment by eprogramming** [comment]
+1

**Comment by eprogramming** [comment]
hi all , 
for my understand...
when this feature enabled so, this : [ejb fraction with method async](https://github.com/wildfly-swarm/wildfly-swarm-examples/blob/master/gradle-mail/src/main/java/org/wildfly/swarm/examples/mail/Mail.java#L27) is not needed anymore right ?

btw I'm not java EE expert

**Comment by eprogramming** [comment]
i mean, no need add EJB Fraction because this will be enabled by JAX-RS fraction is correct ?
thanks

**Comment by thomasandersen77** [comment]
Going out on a limb here, but could not this just be handled by the underlying resteasy implementation by using `@Suspended AsynchronousResponse response` as parameter to the rest-endpoint?

`The @Suspend annotation tells Resteasy that the HTTP request/response should be detached from the currently executing thread and that the current thread should not try to automaticaly process the response.`
https://docs.jboss.org/resteasy/docs/1.0.0.GA/userguide/html/Asynchronous_HTTP_Request_Processing.html

Or have I missed something very essential?

**Comment by eprogramming** [comment]
hi @thomasandersen77 

> but could not this just be handled by the underlying resteasy implementation by using @Suspended AsynchronousResponse response as parameter to the rest-endpoint?

yup this is the point too **(1)**, so that we don't need to add one more jar as dependency ( the ejb fraction to get the async method ) because jax-rs fraction will have it enabled by default **(2)**

thanks

**Comment by thomasandersen77** [comment]
Are you planning to create an example or is it open for others to contribute. Was so fun to contribute with a bit with the Docker example ;)

**Comment by eprogramming** [comment]
@thomasandersen77 go for it ! 
Is open for others to contribute : ]

My plan (now) is to put alpha version in production on my current job

**Comment by thomasandersen77** [comment]
@eprogramming Thanks, I will :) 

Please let me know how stable it is when you've had some traffic on it. Maybe my customer will consider it in a few months as well. As of now we use it to mock an external system in a Docker test environment

**Comment by eprogramming** [comment]
> Please let me know how stable it is when you've had some traffic on it

Ok !

**Comment by bobmcwhirter** [comment]
I think you're right. Mostly this is just to demonstrate that existing jaxrs async stuff actually works. Hopefully no net new code. 

--

**Comment by bobmcwhirter** [comment]
The @Suspend async JAX-RS stuff works as expected.

In a separate example where I'm mucking with NetflixOSS Ribbon, I see it functioning:

https://github.com/wildfly-swarm/wildfly-swarm-examples/blob/master/multiple/events/src/main/java/org/wildfly/swarm/examples/multi/events/EventsResource.java
