### ISSUE TITLE
Centralized Logging

### ISSUE THREAD

**Issue by bobmcwhirter** [wildfly-swarm/wildfly-swarm#76]
Whether LogStash/Elk or something RHQ/Hawkular-based.

**Comment by heiko-braun** [comment]
I guess this boils down to a custom log adapter within the WF logging subsystem? That's probably something @jamezp can comment on.

**Comment by jamezp** [comment]
WildFly can send logs anywhere really. FWIW I did just do a blog post about sending WildFly logs to logstash. http://wildfly.org/news/2015/07/25/Wildfly-And-ELK/

**Comment by kenfinnigan** [comment]
Yep, was planning on using the information in your blog to create a logstash fraction! ;-)

**Comment by kenfinnigan** [comment]
To have your application log to logstash:

* Add dependency to `wildfly-swarm-logstash`
* Configure the `LogstashFraction` inside your `Main` class, by specifying the hostname and port of the logstash server:

```
Container container = new Container();
container.fraction(new LogstashFraction().hostname("localhost").port("8000"));
```

By default, the `LogstashFraction` will create a piece of metadata in the message to logstash with a key of `wildflySwarmNode` and value of `${jboss.node.name}`. The value will default to the hostname of the machine, but can be overridden by specifying `-Djboss.node.name=[name]` on the command line when starting the self executable.

You can also override the key name and value being passed to logstash in the `LogstashFraction` constructor:

```
container.fraction(new LogstashFraction("metadataKey", "metadataValue").hostname("localhost").port("8000"));
```

You can also set as many metadata elements on the message as you desire:

```
new LogstasFraction()
  .metadata("key1", "value1")
  .metadata("key2", "value2");
```

**Comment by jamezp** [comment]
That's awesome Ken! Well done.

**Comment by eprogramming** [comment]
+1

**Comment by bobmcwhirter** [comment]
Addendum:

You can configure it manually, by addding new Fraction().hostname("...").port(...)

or you can avoid explicit compile-time configuration by running your app with:

    -Dswarm.logstash.hostname=...
    -Dswarm.logstash.port=...

If both are not set, there is no default Logstash configuration.  If both properties are set, logstash will be configured and added to your container (assuming you have the wildfly-swarm-logstash dependency).

**Comment by thomasandersen77** [comment]
It would be fantastic if it was possible to do the same with Splunk. A SplunkFraction  :)

**Comment by bobmcwhirter** [comment]
That should be fairly straight-forward if you wanted to adapt the Logstash fraction and contribute it. 

--

**Comment by thomasandersen77** [comment]
On holiday, but will give it a shot :)
