### ISSUE TITLE
Keycloak Integration

### ISSUE THREAD

**Issue by bobmcwhirter** [wildfly-swarm/wildfly-swarm#79]

**Comment by emag** [comment]
+1 !

**Comment by eprogramming** [comment]
+1

**Comment by bobmcwhirter** [comment]
This was included in the alpha4 release.

myDeployment.as(Secured.class)

will find a `keycloak.json` from your classpath and setup keycloak (and munge up a web.xml with some security-contraints).

You can further call combinations of .protect("/path/to/whatever").withMethod("GET").withRoles("admin")

Might need additional improvement, but it works.
