### ISSUE TITLE
Support for the mail subsystem

### ISSUE THREAD

**Issue by eprogramming** [wildfly-swarm/wildfly-swarm#83]
hi all, 
It would be great if i could create a centralized mail service with jax-rs to put in production on my current job.
thanks !

**Comment by kenfinnigan** [comment]
Are you suggesting we create a mail service that has JAX-RS endpoints for sending emails?

If so, I'm not sure that's something we would do as part of WildFly Swarm. Certainly you could use it to build something like that, just not sure it would fit within the project itself

**Comment by bobmcwhirter** [comment]
I think he means the javax.mail stuff with a centralized way to setup the SMTP host for use by apps. Data sources for SMTP basically if I recall. 

--

**Comment by eprogramming** [comment]
> Are you suggesting we create a mail service that has JAX-RS endpoints for sending emails?

no, sorry i updated the description.

add the configuration of the stmp

**Comment by eprogramming** [comment]
> Data sources for SMTP basically

yes

![test](https://cloud.githubusercontent.com/assets/6443576/8549197/cf9b0094-249f-11e5-8d06-a79d5b4a4e45.png)

**Comment by kenfinnigan** [comment]
I'd misunderstood, makes sense now

**Comment by eprogramming** [comment]
@kenfinnigan sorry the problem was my poor written english  (improving...)
thanks ! I'm going to test this right now !

**Comment by eprogramming** [comment]
hi @kenfinnigan getting NameNotFound

`Caused by: javax.naming.NameNotFoundException: mail/ExampleName -- service jboss.naming.context.java.jboss.mail.ExampleName`

**Comment by kenfinnigan** [comment]
@eprogramming Sorry about that, made a few mistakes which are now corrected in HEAD

**Comment by eprogramming** [comment]
@kenfinnigan you fixed !
awesome !
Going to test this by using internal smtp from my job.

**Comment by eprogramming** [comment]
can't test due weird problem on jboss repo
( maybe this is a temporary sync problem )

http://repository.jboss.org/nexus/content/groups/public/commons-lang/commons-lang/2.4/

http://repository.jboss.org/nexus/content/groups/public/commons-lang/commons-lang/2.4/commons-lang-2.4.jar.md5 ( 404 here )

download is frozen (freeze?)

![a](https://cloud.githubusercontent.com/assets/6443576/8576578/6342e3e6-2579-11e5-8358-ea6f3550c227.png)

**Comment by kenfinnigan** [comment]
Is that during build?

If so, possibly a temporary problem

**Comment by eprogramming** [comment]
during wildfly-swarm
 `mvn clean install`
now problem is on another dependency... going to wait until tomorrow

**Comment by eprogramming** [comment]
hi all, just small feedback i tested on my job and working fine.
not in production yet ( because we have others things ofc ) but will.
 
Thanks ! Much more simple to share a programmatic way -- for developers to access configuration too (smtp/port), this is not only about the point of 'microservices'.

in other words:

1) before:
A  dev 'without access ...better: **without need to know**' about jboss-cli commands or standalone.xml config.

2) now:
A  dev can understand 'without read docs' how to put a mail service working just setting internal smtp and port.

got it ? ofc applies for DevOp concept.
