### ISSUE TITLE
Fat JAX-RS Jar in Alpha3 running in Docker fails on execution 

### ISSUE THREAD

**Issue by thomasandersen77** [wildfly-swarm/wildfly-swarm#84]
Hi,

I have another issue related to running in a Docker container. It seems that undertow actually binds to an IP6 address at startup.

````
2015-07-07 15:04:17,390 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-16) WFLYUT0012: Started server default-server.
2015-07-07 15:04:17,431 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-16) WFLYUT0006: Undertow HTTP listener default listening on /0:0:0:0:0:0:0:0:8080
````
 I found a closed Issue that @arun-gupta reported, it said to give the java -jar command a `-Djboss.bind.address=0.0.0.0`. I have also checked the Maven Swarm plugin and `RunMojo` which default binds to `0.0.0.0`. This should be sufficient to make the application it available outside of Docker. Meaning `RUN mvn wildfly-swarm:run` also should work in the Dockerfile.

Also:
Running the `java -jar` command, it seems like my resources (any of my classes really) never get packaged in the jar-file.

```
hota@local.husbanken.no@hota-devpc ~/projects/research/swarm-docker (master)$ cd target/
hota@local.husbanken.no@hota-devpc ~/projects/research/swarm-docker/target (master)$ ls
classes  generated-sources  maven-archiver  maven-status  surefire  SwarmDocker  SwarmDocker-swarm.jar  SwarmDocker.war  wildfly-swarm-archive
hota@local.husbanken.no@hota-devpc ~/projects/research/swarm-docker/target (master)$ java -jar SwarmDocker-swarm.jar 
Exception in thread "main" java.lang.ClassNotFoundException: swarm.SwarmMain from [Module "org.wildfly.swarm.bootstrap:main" from BootModuleLoader@504bae78 for finders [org.wildfly.swarm.bootstrap.modules.BootstrapClasspathModuleFinder@3b764bce, org.wildfly.swarm.bootstrap.modules.BootstrapModuleFinder@759ebb3d, org.wildfly.swarm.bootstrap.modules.ClasspathModuleFinder@484b61fc, org.wildfly.swarm.bootstrap.modules.AppDependenciesModuleFinder@45fe3ee3]]
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:205)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at org.wildfly.swarm.bootstrap.Main.main(Main.java:51)
````
I created a minimal project on Github. [https://github.com/thomasandersen77/swarm-docker](https://github.com/thomasandersen77/swarm-docker)

I have verified this behavior in both 1.0.0.0.Alpha3 and 1.0.0.0.Alpha4-SNAPSHOT (latest from master branch). 

I run Maven 3.3.3 and Java 8. The only way to make it run is from IntelliJ and the main class.

Thank you again for your time!

**Comment by eprogramming** [comment]
weird..
I'm going to learn more about docker to try this too...

**Comment by bobmcwhirter** [comment]
There is also a system property akin to preferIPv4 or such you can set.  But I thought we already set it. 



--

**Comment by thomasandersen77** [comment]
@bobmcwhirter I will try some more tomorrow. @eprogramming: Docker and Wildfly Swarm are such a good match :)

We successfully run Wildfly 8.2 inside Docker in standalone mode. For some of our deployments it is a bit overkill to run a full Wildfly. 

To start Wildfly we give the startup script `-b .0.0.0.0`. Don't know if that is of help?

**Comment by emag** [comment]
@thomasandersen77 

`jar` packaging is needed If you want to use `java -jar SwarmDocker-swarm.jar`.

https://github.com/thomasandersen77/swarm-docker/blob/master/pom.xml#L10

In your [settings.xml](https://github.com/thomasandersen77/swarm-docker/blob/master/settings.xml) , it specifies your own nexus right?

If so, It works in the following step in my environment .

1. war -> jar in pom.xml(as I said)
2. remove(comment out) adding settings.xml in [Dockerfile](https://github.com/thomasandersen77/swarm-docker/blob/master/Dockerfile#L13)
3. `docker-compose up`

And, maybe it would be good in Dockerfile.

* `ENTRYPOINT ["java", "-jar", "/source/target/SwarmDocker-swarm.jar"]` instead of `RUN ...`

Again, `docker-compose up`.

``` sh
$ docker-compose up
Creating swarmdocker_swarm_1...
Building swarm...
Step 0 : FROM java:openjdk-8-jdk
 ...
swarm_1 | 2015-07-07 19:47:04,159 INFO  [org.jboss.as.server] (main) WFLYSRV0010: Deployed "4fd14f4c-d158-49e0-8b5d-19b8607193e8.war" (runtime-name : "4fd14f4c-d158-49e0-8b5d-19b8607193e8.war")
```

``` sh
$ docker ps
CONTAINER ID        IMAGE                      COMMAND                CREATED             STATUS              PORTS                    NAMES
261f48226fc8        swarmdocker_swarm:latest   "java -jar /source/t   18 seconds ago      Up 17 seconds       0.0.0.0:8080->8080/tcp   swarmdocker_swarm_1
```

``` sh
$ curl localhost:8080/resource
bar%
```

**Comment by thomasandersen77** [comment]
@emag 

The docs didn't explain that you needed to change the packaging to `jar`, but I sad I at least didn't try since it was quite obvious.

My internal project had a dependency on
````
        <dependency>
            <groupId>com.jayway.jsonpath</groupId>
            <artifactId>json-path</artifactId>
            <version>2.0.0</version>
            <exclusions>
                <exclusion>
                    <groupId>asm</groupId>
                    <artifactId>asm</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
````
While `wildfly-swarm-jaxrs` had a transitive dependency to `asm-all`. So the exclusion above was necessary to make it work.

@eprogramming @bobmcwhirter Would you like my test-project contributed to `examples`, since I guess I am not the only one experimenting with Docker and Swarm.

@emag Thank you for your help and taking the time to give such a thorough explanation! Saved my week ;)

Againg, thanks for all your help :)

Kind regard,
Thomas

**Comment by emag** [comment]
@thomasandersen77 no problem :)

> since I guess I am not the only one experimenting with Docker and Swarm.

Absolutely!

**Comment by thomasandersen77** [comment]
@emag Excellent! Do I make a pull request on master or Alpha3 branch?

**Comment by emag** [comment]
@thomasandersen77 
I think [wildfly-swarm-examples](https://github.com/wildfly-swarm/wildfly-swarm-examples) is proper for your example PR.

And, the repository target wf-swarm version is [1.0.0.Alpha4-SNAPSHOT](https://github.com/wildfly-swarm/wildfly-swarm-examples/blob/master/pom.xml#L11) for now.

**Comment by thomasandersen77** [comment]
@emag: The parent pom i messing up my mvn build inside docker. Is it allowed to remove the parent pom from my pom (I see that inheriting `version.wildfly-swarm` would be lost)? Or else I would need a Dockerfile at the same level as the root pom.

**Comment by emag** [comment]
>  Is it allowed to remove the parent pom from my pom (I see that inheriting version.wildfly-swarm would be lost)? 

I don't know, but, by preference, it should be sub-module.

> Or else I would need a Dockerfile at the same level as the root pom

Hmm, can you create your example as sub-module like this? perhaps it doesn't mess parent.

``` sh
wildfly-swarm-examples/
├── pom.xml <- add swarm-docker module element
├── swarm-docker
│   ├── Dockerfile
│   ├── README.md
│   ├── docker-compose.yml
│   ├── pom.xml
│   ├── settings.xml <- can remove for other users?
│   └── src
└── wildfly-swarm-examples-parent.iml
```

**Comment by thomasandersen77** [comment]
It will because Docker does not allow you to back reference resources you add for security reasons. 
````
ADD .../pom.xml     /
````
It fails with the following message: 
````
Step 4 : WORKDIR /source
 ---> Using cache
 ---> ee325091919c
Step 5 : ADD ../pom.xml /
Service 'swarm' failed to build: ../pom.xml: no such file or directory
````
So maybe the least intrusive would be a Dockerfile at the same level as the root pom.

**Comment by emag** [comment]
Ahh! Now I'm with you...

Or, how about `ADD SwarmDocker-swarm.jar`  in Dockerfile though users have to do `mvn package` before `docker build` or `docker-compose` ?

e.g.)

``` dockerfile
FROM java:openjdk-8-jdk
EXPOSE 8080
ADD target/SwarmDocker-swarm.jar /opt/SwarmDocker-swarm.jar
ENTRYPOINT ["java", "-jar", "/opt/SwarmDocker-swarm.jar"]
```

**Comment by thomasandersen77** [comment]
Seems to be the only solution. But excellent suggestion! I will fix it and send a pull request when I am of work in a few hours :+1:  

Thanks again :)

**Comment by bobmcwhirter** [comment]
Ha you don't have to use the example parent POM in an example. It's just convenient. 

But for instance the gradle example doesn't use it. 

--

**Comment by thomasandersen77** [comment]
@bobmcwhirter Ok. Thanks. However I solved it like @emag suggested. Running Maven inside the container is a in my experience convenience. The docker image will be smaller when you do not have to have the maven repo inside the image. A matter of preference really :)

**Comment by thomasandersen77** [comment]
@emag @bobmcwhirter 
I sent a pull request but was unable to add reviewers. This my first pull request on Github . Hope I got it right :)

**Comment by bobmcwhirter** [comment]
Can you take a look @kenfinnigan? Hard to review on phone. 

--

**Comment by kenfinnigan** [comment]
@bobmcwhirter get back to your holiday!

Will look at it shortly
