### ISSUE TITLE
JSF

### ISSUE THREAD

**Issue by emag** [wildfly-swarm/wildfly-swarm#85]

**Comment by emag** [comment]
I'm working on creating JSF ShrinWrap example.

https://github.com/emag/wildfly-swarm-examples/tree/jsf-shrinkwrap-example/jsf-shrinkwrap

But, JSF/facelets doesn't work. Any idea?

``` sh
$ mvn clean package && java -jar target/wildfly-swarm-example-jsf-shrinkwrap-swarm.jar
...
... INFO  [org.jboss.as.server.deployment] (MSC service thread 1-1) WFLYSRV0027: Starting deployment of "83ceeb2c-39f4-4eab-aaa5-7725c5d6be2b.war" (runtime-name: "83ceeb2c-39f4-4eab-aaa5-7725c5d6be2b.war")
... INFO  [org.wildfly.extension.undertow] (MSC service thread 1-1) WFLYUT0018: Host default-host starting
... INFO  [javax.enterprise.resource.webcontainer.jsf.config] (ServerService Thread Pool -- 9) Initializing Mojarra 2.2.11-jbossorg-1 20150505-1501 for context ''
... INFO  [org.wildfly.extension.undertow] (ServerService Thread Pool -- 9) WFLYUT0021: Registered web context: /
... INFO  [org.jboss.as.server] (main) WFLYSRV0010: Deployed "83ceeb2c-39f4-4eab-aaa5-7725c5d6be2b.war" (runtime-name : "83ceeb2c-39f4-4eab-aaa5-7725c5d6be2b.war")
```

It seems Mojarra enabled(Initializing Mojarra ~), however, it responses the raw content.

``` sh
$ curl localhost:8080/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

<body>

<ui:composition template="/WEB-INF/template.xhtml">

    <ui:define name="content">
        <h:outputText value="#{message.say()}"/>
    </ui:define>

</ui:composition>

</body>
</html>%
```

**Comment by kenfinnigan** [comment]
Does the example work as a non Shrinkwrap version?

What are the benefits to having a Shrinkwrap version for JSF? Not sure there would be much you would want to "control" for a regular JSF app.

WEB-INF is probably exposed because of the `deployment.staticContent` call, and that's probably also why the xhtml files are being returned un processed, because Undertow is responding with the file content before JSF can process them

**Comment by emag** [comment]
> Does the example work as a non Shrinkwrap version?

Yes, [a xhtml is processed](https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/master/jsf#use).
 
> What are the benefits to having a Shrinkwrap version for JSF? Not sure there would be much you would want to "control" for a regular JSF app.

In most cases, datasource, logging settings. Even if WF-Swarm supports WildFly management interfaces(CLI, Web console) in the future, it is useful programmable settings by fractions. 

> WEB-INF is probably exposed because of the deployment.staticContent call, and that's probably also why the xhtml files are being returned un processed, because Undertow is responding with the file content before JSF can process them

Ok, I got it. You mean, JSF ShrinkWrap version is difficult ?

**Comment by kenfinnigan** [comment]
Shouldn't be difficult, but you don't need the deployment.staticContent call.

If you populate the `WarDeployment` in a similar fashion to JAX-RS examples, it should be fine

**Comment by emag** [comment]
Hmm, I'm not with you...  How can I expose facelets(xhtml) without deployment.staticContent call ?

**Comment by bobmcwhirter** [comment]
Static is served un-modified. Facelets (and jsp) are not really static I think. But I have never done JSF. 

--

**Comment by kenfinnigan** [comment]
Correct @bobmcwhirter, JSF is non static.

@emag you will need to add the xhtml files to Shrinkwrap in a manner such as `war.addAsWebResource()`. I think that's the correct way, it's been a while since I've written Shrinkwrap tests for JSF.

**Comment by emag** [comment]
@bobmcwhirter @kenfinnigan Thank you for your reply! Now I understand it. You're right,  absolutely.

> you will need to add the xhtml files to Shrinkwrap in a manner such as war.addAsWebResource(). I think that's the correct way, it's been a while since I've written Shrinkwrap tests for JSF.

Yes, it works :) I'll send you the PR shortly.
