### ISSUE TITLE
Static content - welcome page 

### ISSUE THREAD

**Issue by guedouarj** [wildfly-swarm/wildfly-swarm#86]
Hello,

I followed this ticket:

https://github.com/wildfly-swarm/wildfly-swarm/issues/49

It seems that the welcome file ( aka index.html or other ) is still not working on the deployed JAR file, however it works with the wildfly-swarm maven plugin.

I always have a 403 Forbidden error when I got to the ROOT context of the app.

http://myapp.com/ -> 403 Forbidden
http://myapp.com/index.html -> OK !
 
I followed this example:

https://github.com/wildfly-swarm/wildfly-swarm-examples/tree/master/static ( JAR deploy )

Thank you for your support !

**Comment by kenfinnigan** [comment]
One slight quirk with the `static` example is that https://github.com/wildfly-swarm/wildfly-swarm-examples/blob/master/static/src/main/java/org/wildfly/swarm/examples/staticcontent/Main.java#L15 tells Undertow to make the deployment available at `/static` and not `/`.

When running the `static` example you should see:

http://myapp.com/ -> 404 Not Found
http://myapp.com/static/ -> OK
http://myapp.com/static/index.html -> OK

The `static-war` example would give the following:

http://myapp.com/ -> OK
http://myapp.com/index.html -> OK

I've just verified the above with the latest HEAD of WildFly Swarm and examples.

Are there any exceptions in the log on startup or when accessing the example?

Ken

**Comment by guedouarj** [comment]
Nope I have no exceptions...

and http://myapp.com/ gives me 403 Forbidden, I tested with packaging JAR on the pom file.
But normally we should be able to get http://myapp.com/  working, this is just a ROOT context "/".

On a standard JBOSS config we put the context to "/".

Anyway its not really a problem as we can use a proxy server to serve URL like /static...

**Comment by kenfinnigan** [comment]
You can easily change the code in the `Main` class to set the context to be `/` instead of `/static`.

Which O/S are you testing on?

**Comment by guedouarj** [comment]
Ubuntu linux.

**Comment by kenfinnigan** [comment]
That's weird.

I'm on the same and don't have any issues with those two examples

**Comment by guedouarj** [comment]
This is really strange then... And it works well with the wildfly swarm maven plugin, but not with the deployed jar ( *.-swarm.jar ).

**Comment by emag** [comment]
@guedouarj Do you use latest HEAD of WildFly Swarm ?

**Comment by guedouarj** [comment]
Yes the 1.0.0.Alpha3

**Comment by emag** [comment]
Oh, I can reproduce it at 1.0.0.Alpha3 in the following steps. 
Though I don't know why the reason, the issue is fixed at HEAD at least. Please give it a try.

``` sh
$ git clone https://github.com/wildfly-swarm/wildfly-swarm-examples && cd wildfly-swarm-examples
$ sed -i "s/Alpha4-SNAPSHOT/Alpha3/" pom.xml
$ cd static-war
$ mvn clean package && java -jar target/wildfly-swarm-example-static-war-swarm.jar
```

``` sh
$ curl localhost:8080 -I 
HTTP/1.1 403 Forbidden
...

$ curl localhost:8080/ -I
HTTP/1.1 403 Forbidden
...

$ curl localhost:8080/index.html -I
HTTP/1.1 404 Not Found <- Ugh, weird...
...
```

**Comment by emag** [comment]
Ah, I'd misunderstood. @guedouarj use static example, not static-war.

static example is OK at Alpha3 in my environment...

``` sh
$ cat wildfly-swarm-examples/pom.xml | grep "<version.wildfly-swarm>"
    <version.wildfly-swarm>1.0.0.Alpha3</version.wildfly-swarm>
$ cd static
$ mvn clean package && java -jar target/wildfly-swarm-example-static-swarm.jar
```

``` sh
$ curl localhost:8080/static/
<html>
  <head>
      <title>Howdy!</title>
  </head>
  <body>
    <h1>Static content!</h1>
  </body>
</html>
```
