### ISSUE TITLE
Document the modules bootstrap mechnisms 

### ISSUE THREAD

**Issue by heiko-braun** [wildfly-swarm/wildfly-swarm#96]
It looks like swarm uses a diferent approach to boostrap the modules depending wether it's running embedded or as fat jar. Can someone briefly explain the mechanism behind the BootModuleLoader, it's ModuleFinders within the context of an embedded swarm instance and the context of a fat jar?

**Comment by heiko-braun** [comment]
This is somewhat related my question at #95

**Comment by bobmcwhirter** [comment]
I think this is answered by #95.
