### ISSUE TITLE
RFE: Moving the documentation to gitbooks.io

### ISSUE THREAD

**Issue by heiko-braun** [wildfly-swarm/wildfly-swarm#97]
Several jboss projects have made good experience with hosting the project documentation at gitbooks.io. It basically boils down to markdown documents that are kept with the swarm sources and some git hooks that publish the documentation whenever a commit to the documentation is received.

An example project documentation can be found here:
http://fabric8.io/gitbook/developer.html
(Note that this project uses a custom domain)

I am volunteering to do the initial setup if you think this is reasonable.

**Comment by kenfinnigan** [comment]
Currently our plan was to add documentation to http://wildfly.org/swarm/

I think the main reasoning was not having to spend time setting up a docs site.

Was it more than that @bobmcwhirter ?

**Comment by bobmcwhirter** [comment]
Yah, ultimately I'm lazy.  If we can do something that works easily and is published to GitHub sites or whatnot, I'm absolutely game.

I do think keeping http://wildfly.org/swarm/ as our web-presence is good, even if docs move to a different documentation site. 

But I don't want to deal with infrastructure, if I can help it.

**Comment by bobmcwhirter** [comment]
Documentation is starting to migrate to this GitHub repository:

https://github.com/wildfly-swarm/wildfly-swarm-users-guide

Which is wired up to this GitBook:

http://wildfly-swarm.gitbooks.io/wildfly-swarm-users-guide/content/

Pull-requests against GitHub will work.  If you (meaning anyone!) want access to the GitBook online editor, please just contact me or @kenfinnigan.
