### ISSUE TITLE
PEP: Generating the API's to configure the Wildfly subsystems

### ISSUE THREAD

**Issue by heiko-braun** [wildfly-swarm/wildfly-swarm#98]
( This is a project enhancement proposal, based on a discussion between @bobmcwhirter and @n1hility. I am merely trying to capture the ideas and throw in some thoughts on my own)

## Abstract

Provide an extension to swarm that can generate Java API's to build and execute the management operations needed to configure wildfly subsystems. 

The API's to configure subsystems will be generated from the wildfly management model meta data and result in a versioned Java API to be used by swarm fractions.

## Motivation

Swarm currently only supports a subset of the configuration options for subsystems embodied by fractions. Furthermore any change to the wildfly management API's imposes a maintenance effort to keep the fraction code in sync with the management API's. A generated API should provide full support for all configuration options and significantly reduce the maintence burden.

**Comment by heiko-braun** [comment]
Versioned Java API: the resulting API's can be distinguished by management model  and/or subsystem version.  The model and subsystem versions correspnd to the different wildfly releases.

**Comment by bobmcwhirter** [comment]
So I'd hope we could avoid versioning of the Java API, but I dunno exactly what the guarantees are.

Basically, if standalone.xml is backwards compatible (across minor versions?  major?) I'd think our Java API could also.

Additionally, at this point, each release of WildFly-Swarm is intimately pinned to a specific version of WildFly itself since everything is resolved through maven transitive dependencies.

-swarm version X.1.5 points to wildfly version Y.0.2

When/if the day comes that -swarm is simply a part of WildFly itself, then it'll of course be even more closely tied, in terms of version numbering.

**Comment by heiko-braun** [comment]
I see two ways versioning can be addressed:

a) version the packages (i.e. org.wildfly.model.123.datasources)
b) version the maven artefacts according to the wilfly version (i.e. org.wildfly.model:datasources:jar:123

The later has the benefit that the swarm fraction would not be coupled to a version explicitly. A swarm fraction could however become incompatible with the config API's. But considering WF's compatibility requirements this should not happen often.

**Comment by heiko-braun** [comment]
> Re: So I'd hope we could avoid versioning of the Java API

What are your concerns? I did include versioning because I believe this would simplify updating to newer WF versions

**Comment by bobmcwhirter** [comment]
My concern is if someone uses -swarm to write 100 microservices, each with their own main() and configuring something.  If we change the name of an attribute or whatnot, then they have to not only rebuild 100 services, but also edit them all.

If the API changes were purely additive, then only a rebuild would be required.

I think @n1lhility also mentioned that there's already a "no changes allowed" policy in WF itself, except additions.  Any major changes require completely newly-named subsystems or backwards compatible parsers or whatnot, I think?

Then again, I'm pretty ignorant.

If we have to version, then we have to version.  But if we can keep the API as additive-only across versions, that's even better.

**Comment by heiko-braun** [comment]
Right, there is a strict backwards compatibility requirement in WF. That means newer versions the generated API will mostly have additional attributes. In some cases WF deprecates attributes or renames them. In case of deprecation this would be represented in the Java API as well. Renamed attributes in WF are subject to be aliased. This case is handled by WF itself. So you can still refer to the previous attribute name but the WF will redirect the invocation to the alias target. 

But for all of these cases I don't see any problems with swarm clients depending specific API names. We should be able to provide the same or similar compatibility guarantees in the generated java API  liek we do in the management model.

**Comment by heiko-braun** [comment]
I guess the bottom line, with regard to the question of versioning or not, is that the version allows for an explicit alignment with a target WF version. And it acts as a point of reference for users that need a landmark to identify new or deprecated elements in that API.

**Comment by kenfinnigan** [comment]
It may not have been mentioned previously, but @bobmcwhirter and I were thinking of versioning WildFly Swarm in line with the WildFly version it requires.

If we do that, is there a need for the generated API to be versioned that way? As then the link between a WildFly Swarm and WildFly version is explicit at the project level.

**Comment by n1hility** [comment]
So the management model compatibilty policy is that a subsystem's management model can never break compatibility. It can only add additional resources, attributes and operations. Changes are possible but only if they are compatible. For example if something allows a range of 1-10, it can be changed to allow a range of 1-20. If the compatibility contract needs to change then the subsystem has to be renamed. 

We can however drop old subsystems at various points. Those older dropped subsystems are still supported in domain mode to allow newer versions of WildFly running as a domain controller to manage older versions of WildFly.  Additionally we are starting to provide migration operations that convert from a dead subsystem to a newer one, which works in both modes. The main intention is that provisioning code can be reused even with a major transition.

That said we have had compatibility bugs (which were subsequently fixed), and in the early days we were less strict about compatibility. Now with it widely deployed over a long version history in both the community and in the product we just can't afford to be lax about it.

Note that the management model compatibility is not the same as the schema versions. We have to bump schema versions for every change to get the latest element and attribute definitions.

**Comment by heiko-braun** [comment]
@kenfinnigan 

> we were thinking of versioning WildFly Swarm in line with the WildFly version it requires.

I think this doesn't change anything. The way I see it the set of configurable attributes is ultimatley defined by WF. Any new release may add (backwards compatible) changes to the management API. This means that swarm has to upgrade to the new (generated) management API's when moving to a newer WF version. At least if we want the swarm configuration to be en par with the wildfly subsystems, which I assumed is the motivation for generating the API's in the first place.

**Comment by heiko-braun** [comment]
@bobmcwhirter , @kenfinnigan 

let's turn it around: newer WF releases may introduce additional configurable attributes. How would you express this if not ny using a versioneed API?

**Comment by bobmcwhirter** [comment]
Yah, but I think the point is, assuming -swarm version numbering matches wf version numbering, then...

configuration objects in wildfly-swarm-10.0.2 will exactly match the options available in wildfly-10.0.2.

If new things get added to wildfly-10.0.3, then the classes in wildfly-swarm's 10.0.3 will also accommodate them, without having to change package names or add any other version grist into the configuration object names.

e.g., LoggingThing.setHappy(boolean) might exist on 10.0.3 of -swarm, but not 10.0.2, if it was only added to WildFly 10.0.3.

**Comment by bobmcwhirter** [comment]
I think ultimately, the "versioning" of the API changes is done by maven artifact versions.

-swarm-10.0.3.jar has the newer/extra attributes that are lacking in -swarm-10.0.2.jar.

**Comment by heiko-braun** [comment]
> "versioning" of the API changes is done by maven artifact versions.

yes, exactly.

**Comment by heiko-braun** [comment]
> version grist 

ok, maybe we should nail down some of the things that should not happen:

- change of java attribute names
- change of java attribute types
- change of package names
- removal of attributes
- removal of classes (deprecation is an exception)

Anything else you can think of that might break existing swarm applications?

**Comment by bobmcwhirter** [comment]
I can't think of anything else right off hand.

fwiw, I'm not yet actually worried about breaking changes, since, quite frankly, we break the crap out of stuff with each release currently.  Hooray Alpha releases!

But once we start nailing down stuff, it'll matter more.

**Comment by lance** [comment]
The only other breaking change I can think of is if possible attribute values change. Taking your example above, @heiko-braun. If something allows a range of 1-10, it cannot be changed to allow a range of 1-8.

**Comment by heiko-braun** [comment]
Here's a first draft of some of the ideas turned into code: https://github.com/heiko-braun/api-gen

It breaks into three pieces: 

- A generator (turns wildfly meta data into a java object model)
- The config lib (output of the generator. represents parts of the management model)
- A marshalling layer (turns java into dmr and vice versa)

It's in it's early stages, but should allow us to further specifiy how we want to apporach it (i.e. how the Java API looks like).

**Comment by heiko-braun** [comment]
@lance I've added a larger commit to support explicit keys for resources (actor argument) and implict keys in case of singleton resources (only one predefined instance. encoded key): https://github.com/heiko-braun/api-gen/commit/619a744dec077cd35b1ffa3603add55a87ccce24

Alongside  these changes I introduced subpackages that more a less try to reflect a resource hierarchy. 

Here's an example of an explicit key:

```
@Address("/subsystem=datasources/data-source=*")
public class DataSource {

public DataSource(String key) {
		this.key = key;
}
[...]
}
```

Another ones using implicit keys (singleton resources). Singleton resources only allow a single resource with a predfined name in the resource tree:
```
@Address("/subsystem=logging/root-logger=ROOT")
@Implicit
public class Root {

	private String key;
	private String filterSpec;
	private String level;

	public Root() {
		this.key = "ROOT";
	}
[...]
}
```

**Comment by heiko-braun** [comment]
The next thing I am going to look into is to marshall a complete object hierarchy into DMR. The primary output should be a sequence of ADD operations, that will be executed to provide the setup the server configuration. 

An alternative (not sure if it's needed) is a marshaller that creates hierarchical DMR structure (i.e. a complex nested resources representation).

Pseudo API for the two approaches:

Sequential Strategy:
```
Marshaller m = Marshaller.create(Strategy.SEQUENTIAL);
List<ModelNode> addOperations = m.marshall( <Object hierarchy> );
```

Hierachical strategy:
```
Marshaller m = Marshaller.create(Strategy.HIERACHICAL);
ModelNode resource = m.marshall( <Object hierarchy> );
```

**Comment by bobmcwhirter** [comment]
We currently work with a flat List<ModelNode> when we give it to the AS at boot-time to OP=add everything.  That'd be the most straight-forward for us.  But then again I've never worked with a hierarchy of objects from a single root.  If that also is usable to boot the AS, then I imagine we could make it work also.

But generally, lists seem easier to deal with.

**Comment by lance** [comment]
This is great - thank you! I was struggling with how to deal with singleton
resources yesterday. This clarifies things a bit for me.

Lance Ball
http://lanceball.com

**Comment by heiko-braun** [comment]
@lance yes, they now get detected when the resource description is parsed. ResourceDescription now carries that info through the processing chain: 
https://github.com/heiko-braun/api-gen/blob/master/generator/src/main/java/org/wildfly/apigen/model/ResourceDescription.java#L177

This allows the SourceFactory to treat singleton resources differently (i.e. use single accessors instead of collections):
https://github.com/heiko-braun/api-gen/blob/master/generator/src/main/java/org/wildfly/apigen/generator/SourceFactory.java#L292

**Comment by heiko-braun** [comment]
@lance maybe you can comment on the package structures? Do you see any room for improvements?

**Comment by lance** [comment]
@heiko-braun I like that you have moved the subsystems into their own `subsystem` package. But I'm not sure about continued subpackaging after that. A couple of things that I'm noticing. I think because these objects are getting subpackaged, we end up with some duplicates. For example, in the `logging` subsystem we have `org.wildfly.swarm.config.logging.subsystem.asyncHandler.AsyncHandler` and also `org.wildfly.swarm.config.logging.subsystem.loggingProfile.asyncHandler.AsyncHandler`. These are functionally identical, and differ only in package name.

<img width="414" alt="screenshot 2015-08-13 15 15 36" src="https://cloud.githubusercontent.com/assets/15952/9259296/4689a994-41ce-11e5-9b8c-9e9f5bd5883c.png">

I also was thinking that perhaps leaf nodes and perhaps even singletons don't need a subpackage.

<img width="398" alt="screenshot 2015-08-13 15 24 36" src="https://cloud.githubusercontent.com/assets/15952/9259939/aaa20f12-41d2-11e5-85b8-96e06ff58cd4.png">

Instead of `org.wildfly.swarm.config.mail.subsystem.mailSession.custom.Custom` it could be ``org.wildfly.swarm.config.mail.subsystem.mailSession.Custom`.

**Comment by n1hility** [comment]
I am stoked at the progress guys! Cool stuff.

**Comment by heiko-braun** [comment]
@lance 
> we end up with some duplicates. 

These may be functionally identical, but are actually different resources in the model (see @Address on those classes). Detecting these cases and re-using java types for resources at different address locations in the model would be nice, but overall I think the effort is not worth it:

- determining the equality of two resources would complicate the parsing routines
- re-using java types for different resource addresses would complicate the marshalling unmarshalling

Overall these situations are edge cases and not the norm. Therefore I wouls suggest we leave it as is, for the benefit of having a much more simple ans straightforward way to parse the model, generate the classes and marshall to and from DMR.

**Comment by bobmcwhirter** [comment]
Closing, because it's being done pretty well and integrated.  Progress continues, of course.

Thanks @lance and @heiko-braun !
